/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag72
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag72 {
  @SerializedName("block4Tag72Nar1")
  private String block4Tag72Nar1 = null;

  @SerializedName("block4Tag72Nar2")
  private String block4Tag72Nar2 = null;

  @SerializedName("block4Tag72Nar3")
  private String block4Tag72Nar3 = null;

  @SerializedName("block4Tag72Nar4")
  private String block4Tag72Nar4 = null;

  @SerializedName("block4Tag72Nar5")
  private String block4Tag72Nar5 = null;

  @SerializedName("block4Tag72Nar6")
  private String block4Tag72Nar6 = null;

  public Block4Tag72 block4Tag72Nar1(String block4Tag72Nar1) {
    this.block4Tag72Nar1 = block4Tag72Nar1;
    return this;
  }

   /**
   * Get block4Tag72Nar1
   * @return block4Tag72Nar1
  **/
  @Schema(description = "")
  public String getBlock4Tag72Nar1() {
    return block4Tag72Nar1;
  }

  public void setBlock4Tag72Nar1(String block4Tag72Nar1) {
    this.block4Tag72Nar1 = block4Tag72Nar1;
  }

  public Block4Tag72 block4Tag72Nar2(String block4Tag72Nar2) {
    this.block4Tag72Nar2 = block4Tag72Nar2;
    return this;
  }

   /**
   * Get block4Tag72Nar2
   * @return block4Tag72Nar2
  **/
  @Schema(description = "")
  public String getBlock4Tag72Nar2() {
    return block4Tag72Nar2;
  }

  public void setBlock4Tag72Nar2(String block4Tag72Nar2) {
    this.block4Tag72Nar2 = block4Tag72Nar2;
  }

  public Block4Tag72 block4Tag72Nar3(String block4Tag72Nar3) {
    this.block4Tag72Nar3 = block4Tag72Nar3;
    return this;
  }

   /**
   * Get block4Tag72Nar3
   * @return block4Tag72Nar3
  **/
  @Schema(description = "")
  public String getBlock4Tag72Nar3() {
    return block4Tag72Nar3;
  }

  public void setBlock4Tag72Nar3(String block4Tag72Nar3) {
    this.block4Tag72Nar3 = block4Tag72Nar3;
  }

  public Block4Tag72 block4Tag72Nar4(String block4Tag72Nar4) {
    this.block4Tag72Nar4 = block4Tag72Nar4;
    return this;
  }

   /**
   * Get block4Tag72Nar4
   * @return block4Tag72Nar4
  **/
  @Schema(description = "")
  public String getBlock4Tag72Nar4() {
    return block4Tag72Nar4;
  }

  public void setBlock4Tag72Nar4(String block4Tag72Nar4) {
    this.block4Tag72Nar4 = block4Tag72Nar4;
  }

  public Block4Tag72 block4Tag72Nar5(String block4Tag72Nar5) {
    this.block4Tag72Nar5 = block4Tag72Nar5;
    return this;
  }

   /**
   * Get block4Tag72Nar5
   * @return block4Tag72Nar5
  **/
  @Schema(description = "")
  public String getBlock4Tag72Nar5() {
    return block4Tag72Nar5;
  }

  public void setBlock4Tag72Nar5(String block4Tag72Nar5) {
    this.block4Tag72Nar5 = block4Tag72Nar5;
  }

  public Block4Tag72 block4Tag72Nar6(String block4Tag72Nar6) {
    this.block4Tag72Nar6 = block4Tag72Nar6;
    return this;
  }

   /**
   * Get block4Tag72Nar6
   * @return block4Tag72Nar6
  **/
  @Schema(description = "")
  public String getBlock4Tag72Nar6() {
    return block4Tag72Nar6;
  }

  public void setBlock4Tag72Nar6(String block4Tag72Nar6) {
    this.block4Tag72Nar6 = block4Tag72Nar6;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag72 block4Tag72 = (Block4Tag72) o;
    return Objects.equals(this.block4Tag72Nar1, block4Tag72.block4Tag72Nar1) &&
        Objects.equals(this.block4Tag72Nar2, block4Tag72.block4Tag72Nar2) &&
        Objects.equals(this.block4Tag72Nar3, block4Tag72.block4Tag72Nar3) &&
        Objects.equals(this.block4Tag72Nar4, block4Tag72.block4Tag72Nar4) &&
        Objects.equals(this.block4Tag72Nar5, block4Tag72.block4Tag72Nar5) &&
        Objects.equals(this.block4Tag72Nar6, block4Tag72.block4Tag72Nar6);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag72Nar1, block4Tag72Nar2, block4Tag72Nar3, block4Tag72Nar4, block4Tag72Nar5, block4Tag72Nar6);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag72 {\n");
    
    sb.append("    block4Tag72Nar1: ").append(toIndentedString(block4Tag72Nar1)).append("\n");
    sb.append("    block4Tag72Nar2: ").append(toIndentedString(block4Tag72Nar2)).append("\n");
    sb.append("    block4Tag72Nar3: ").append(toIndentedString(block4Tag72Nar3)).append("\n");
    sb.append("    block4Tag72Nar4: ").append(toIndentedString(block4Tag72Nar4)).append("\n");
    sb.append("    block4Tag72Nar5: ").append(toIndentedString(block4Tag72Nar5)).append("\n");
    sb.append("    block4Tag72Nar6: ").append(toIndentedString(block4Tag72Nar6)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
