/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag52
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag52 {
  @SerializedName("block4Tag52aAcct")
  private String block4Tag52aAcct = null;

  @SerializedName("block4Tag52aBic")
  private String block4Tag52aBic = null;

  @SerializedName("block4Tag52aDcmark")
  private String block4Tag52aDcmark = null;

  @SerializedName("block4Tag52dAcct")
  private String block4Tag52dAcct = null;

  @SerializedName("block4Tag52dDcmark")
  private String block4Tag52dDcmark = null;

  @SerializedName("block4Tag52dNameAddr")
  private String block4Tag52dNameAddr = null;

  public Block4Tag52 block4Tag52aAcct(String block4Tag52aAcct) {
    this.block4Tag52aAcct = block4Tag52aAcct;
    return this;
  }

   /**
   * Get block4Tag52aAcct
   * @return block4Tag52aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag52aAcct() {
    return block4Tag52aAcct;
  }

  public void setBlock4Tag52aAcct(String block4Tag52aAcct) {
    this.block4Tag52aAcct = block4Tag52aAcct;
  }

  public Block4Tag52 block4Tag52aBic(String block4Tag52aBic) {
    this.block4Tag52aBic = block4Tag52aBic;
    return this;
  }

   /**
   * Get block4Tag52aBic
   * @return block4Tag52aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag52aBic() {
    return block4Tag52aBic;
  }

  public void setBlock4Tag52aBic(String block4Tag52aBic) {
    this.block4Tag52aBic = block4Tag52aBic;
  }

  public Block4Tag52 block4Tag52aDcmark(String block4Tag52aDcmark) {
    this.block4Tag52aDcmark = block4Tag52aDcmark;
    return this;
  }

   /**
   * Get block4Tag52aDcmark
   * @return block4Tag52aDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag52aDcmark() {
    return block4Tag52aDcmark;
  }

  public void setBlock4Tag52aDcmark(String block4Tag52aDcmark) {
    this.block4Tag52aDcmark = block4Tag52aDcmark;
  }

  public Block4Tag52 block4Tag52dAcct(String block4Tag52dAcct) {
    this.block4Tag52dAcct = block4Tag52dAcct;
    return this;
  }

   /**
   * Get block4Tag52dAcct
   * @return block4Tag52dAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag52dAcct() {
    return block4Tag52dAcct;
  }

  public void setBlock4Tag52dAcct(String block4Tag52dAcct) {
    this.block4Tag52dAcct = block4Tag52dAcct;
  }

  public Block4Tag52 block4Tag52dDcmark(String block4Tag52dDcmark) {
    this.block4Tag52dDcmark = block4Tag52dDcmark;
    return this;
  }

   /**
   * Get block4Tag52dDcmark
   * @return block4Tag52dDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag52dDcmark() {
    return block4Tag52dDcmark;
  }

  public void setBlock4Tag52dDcmark(String block4Tag52dDcmark) {
    this.block4Tag52dDcmark = block4Tag52dDcmark;
  }

  public Block4Tag52 block4Tag52dNameAddr(String block4Tag52dNameAddr) {
    this.block4Tag52dNameAddr = block4Tag52dNameAddr;
    return this;
  }

   /**
   * Get block4Tag52dNameAddr
   * @return block4Tag52dNameAddr
  **/
  @Schema(description = "")
  public String getBlock4Tag52dNameAddr() {
    return block4Tag52dNameAddr;
  }

  public void setBlock4Tag52dNameAddr(String block4Tag52dNameAddr) {
    this.block4Tag52dNameAddr = block4Tag52dNameAddr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag52 block4Tag52 = (Block4Tag52) o;
    return Objects.equals(this.block4Tag52aAcct, block4Tag52.block4Tag52aAcct) &&
        Objects.equals(this.block4Tag52aBic, block4Tag52.block4Tag52aBic) &&
        Objects.equals(this.block4Tag52aDcmark, block4Tag52.block4Tag52aDcmark) &&
        Objects.equals(this.block4Tag52dAcct, block4Tag52.block4Tag52dAcct) &&
        Objects.equals(this.block4Tag52dDcmark, block4Tag52.block4Tag52dDcmark) &&
        Objects.equals(this.block4Tag52dNameAddr, block4Tag52.block4Tag52dNameAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag52aAcct, block4Tag52aBic, block4Tag52aDcmark, block4Tag52dAcct, block4Tag52dDcmark, block4Tag52dNameAddr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag52 {\n");
    
    sb.append("    block4Tag52aAcct: ").append(toIndentedString(block4Tag52aAcct)).append("\n");
    sb.append("    block4Tag52aBic: ").append(toIndentedString(block4Tag52aBic)).append("\n");
    sb.append("    block4Tag52aDcmark: ").append(toIndentedString(block4Tag52aDcmark)).append("\n");
    sb.append("    block4Tag52dAcct: ").append(toIndentedString(block4Tag52dAcct)).append("\n");
    sb.append("    block4Tag52dDcmark: ").append(toIndentedString(block4Tag52dDcmark)).append("\n");
    sb.append("    block4Tag52dNameAddr: ").append(toIndentedString(block4Tag52dNameAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
