/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag56
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag56 {
  @SerializedName("block4Tag56aAcct")
  private String block4Tag56aAcct = null;

  @SerializedName("block4Tag56aBic")
  private String block4Tag56aBic = null;

  @SerializedName("block4Tag56aDcmark")
  private String block4Tag56aDcmark = null;

  @SerializedName("block4Tag56dAcct")
  private String block4Tag56dAcct = null;

  @SerializedName("block4Tag56dDcmark")
  private String block4Tag56dDcmark = null;

  @SerializedName("block4Tag56dNameAddr")
  private String block4Tag56dNameAddr = null;

  public Block4Tag56 block4Tag56aAcct(String block4Tag56aAcct) {
    this.block4Tag56aAcct = block4Tag56aAcct;
    return this;
  }

   /**
   * Get block4Tag56aAcct
   * @return block4Tag56aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag56aAcct() {
    return block4Tag56aAcct;
  }

  public void setBlock4Tag56aAcct(String block4Tag56aAcct) {
    this.block4Tag56aAcct = block4Tag56aAcct;
  }

  public Block4Tag56 block4Tag56aBic(String block4Tag56aBic) {
    this.block4Tag56aBic = block4Tag56aBic;
    return this;
  }

   /**
   * Get block4Tag56aBic
   * @return block4Tag56aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag56aBic() {
    return block4Tag56aBic;
  }

  public void setBlock4Tag56aBic(String block4Tag56aBic) {
    this.block4Tag56aBic = block4Tag56aBic;
  }

  public Block4Tag56 block4Tag56aDcmark(String block4Tag56aDcmark) {
    this.block4Tag56aDcmark = block4Tag56aDcmark;
    return this;
  }

   /**
   * Get block4Tag56aDcmark
   * @return block4Tag56aDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag56aDcmark() {
    return block4Tag56aDcmark;
  }

  public void setBlock4Tag56aDcmark(String block4Tag56aDcmark) {
    this.block4Tag56aDcmark = block4Tag56aDcmark;
  }

  public Block4Tag56 block4Tag56dAcct(String block4Tag56dAcct) {
    this.block4Tag56dAcct = block4Tag56dAcct;
    return this;
  }

   /**
   * Get block4Tag56dAcct
   * @return block4Tag56dAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag56dAcct() {
    return block4Tag56dAcct;
  }

  public void setBlock4Tag56dAcct(String block4Tag56dAcct) {
    this.block4Tag56dAcct = block4Tag56dAcct;
  }

  public Block4Tag56 block4Tag56dDcmark(String block4Tag56dDcmark) {
    this.block4Tag56dDcmark = block4Tag56dDcmark;
    return this;
  }

   /**
   * Get block4Tag56dDcmark
   * @return block4Tag56dDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag56dDcmark() {
    return block4Tag56dDcmark;
  }

  public void setBlock4Tag56dDcmark(String block4Tag56dDcmark) {
    this.block4Tag56dDcmark = block4Tag56dDcmark;
  }

  public Block4Tag56 block4Tag56dNameAddr(String block4Tag56dNameAddr) {
    this.block4Tag56dNameAddr = block4Tag56dNameAddr;
    return this;
  }

   /**
   * Get block4Tag56dNameAddr
   * @return block4Tag56dNameAddr
  **/
  @Schema(description = "")
  public String getBlock4Tag56dNameAddr() {
    return block4Tag56dNameAddr;
  }

  public void setBlock4Tag56dNameAddr(String block4Tag56dNameAddr) {
    this.block4Tag56dNameAddr = block4Tag56dNameAddr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag56 block4Tag56 = (Block4Tag56) o;
    return Objects.equals(this.block4Tag56aAcct, block4Tag56.block4Tag56aAcct) &&
        Objects.equals(this.block4Tag56aBic, block4Tag56.block4Tag56aBic) &&
        Objects.equals(this.block4Tag56aDcmark, block4Tag56.block4Tag56aDcmark) &&
        Objects.equals(this.block4Tag56dAcct, block4Tag56.block4Tag56dAcct) &&
        Objects.equals(this.block4Tag56dDcmark, block4Tag56.block4Tag56dDcmark) &&
        Objects.equals(this.block4Tag56dNameAddr, block4Tag56.block4Tag56dNameAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag56aAcct, block4Tag56aBic, block4Tag56aDcmark, block4Tag56dAcct, block4Tag56dDcmark, block4Tag56dNameAddr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag56 {\n");
    
    sb.append("    block4Tag56aAcct: ").append(toIndentedString(block4Tag56aAcct)).append("\n");
    sb.append("    block4Tag56aBic: ").append(toIndentedString(block4Tag56aBic)).append("\n");
    sb.append("    block4Tag56aDcmark: ").append(toIndentedString(block4Tag56aDcmark)).append("\n");
    sb.append("    block4Tag56dAcct: ").append(toIndentedString(block4Tag56dAcct)).append("\n");
    sb.append("    block4Tag56dDcmark: ").append(toIndentedString(block4Tag56dDcmark)).append("\n");
    sb.append("    block4Tag56dNameAddr: ").append(toIndentedString(block4Tag56dNameAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
