/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Block4Tag70to71
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag70to71 {
  @SerializedName("block4Tag70Nar1")
  private String block4Tag70Nar1 = null;

  @SerializedName("block4Tag70Nar2")
  private String block4Tag70Nar2 = null;

  @SerializedName("block4Tag70Nar3")
  private String block4Tag70Nar3 = null;

  @SerializedName("block4Tag70Nar4")
  private String block4Tag70Nar4 = null;

  @SerializedName("block4Tag71a")
  private String block4Tag71a = null;

  @SerializedName("block4Tag71gCurrency")
  private String block4Tag71gCurrency = null;

  @SerializedName("block4Tag71gReceivCharge")
  private BigDecimal block4Tag71gReceivCharge = null;

  public Block4Tag70to71 block4Tag70Nar1(String block4Tag70Nar1) {
    this.block4Tag70Nar1 = block4Tag70Nar1;
    return this;
  }

   /**
   * Get block4Tag70Nar1
   * @return block4Tag70Nar1
  **/
  @Schema(description = "")
  public String getBlock4Tag70Nar1() {
    return block4Tag70Nar1;
  }

  public void setBlock4Tag70Nar1(String block4Tag70Nar1) {
    this.block4Tag70Nar1 = block4Tag70Nar1;
  }

  public Block4Tag70to71 block4Tag70Nar2(String block4Tag70Nar2) {
    this.block4Tag70Nar2 = block4Tag70Nar2;
    return this;
  }

   /**
   * Get block4Tag70Nar2
   * @return block4Tag70Nar2
  **/
  @Schema(description = "")
  public String getBlock4Tag70Nar2() {
    return block4Tag70Nar2;
  }

  public void setBlock4Tag70Nar2(String block4Tag70Nar2) {
    this.block4Tag70Nar2 = block4Tag70Nar2;
  }

  public Block4Tag70to71 block4Tag70Nar3(String block4Tag70Nar3) {
    this.block4Tag70Nar3 = block4Tag70Nar3;
    return this;
  }

   /**
   * Get block4Tag70Nar3
   * @return block4Tag70Nar3
  **/
  @Schema(description = "")
  public String getBlock4Tag70Nar3() {
    return block4Tag70Nar3;
  }

  public void setBlock4Tag70Nar3(String block4Tag70Nar3) {
    this.block4Tag70Nar3 = block4Tag70Nar3;
  }

  public Block4Tag70to71 block4Tag70Nar4(String block4Tag70Nar4) {
    this.block4Tag70Nar4 = block4Tag70Nar4;
    return this;
  }

   /**
   * Get block4Tag70Nar4
   * @return block4Tag70Nar4
  **/
  @Schema(description = "")
  public String getBlock4Tag70Nar4() {
    return block4Tag70Nar4;
  }

  public void setBlock4Tag70Nar4(String block4Tag70Nar4) {
    this.block4Tag70Nar4 = block4Tag70Nar4;
  }

  public Block4Tag70to71 block4Tag71a(String block4Tag71a) {
    this.block4Tag71a = block4Tag71a;
    return this;
  }

   /**
   * Get block4Tag71a
   * @return block4Tag71a
  **/
  @Schema(description = "")
  public String getBlock4Tag71a() {
    return block4Tag71a;
  }

  public void setBlock4Tag71a(String block4Tag71a) {
    this.block4Tag71a = block4Tag71a;
  }

  public Block4Tag70to71 block4Tag71gCurrency(String block4Tag71gCurrency) {
    this.block4Tag71gCurrency = block4Tag71gCurrency;
    return this;
  }

   /**
   * Get block4Tag71gCurrency
   * @return block4Tag71gCurrency
  **/
  @Schema(description = "")
  public String getBlock4Tag71gCurrency() {
    return block4Tag71gCurrency;
  }

  public void setBlock4Tag71gCurrency(String block4Tag71gCurrency) {
    this.block4Tag71gCurrency = block4Tag71gCurrency;
  }

  public Block4Tag70to71 block4Tag71gReceivCharge(BigDecimal block4Tag71gReceivCharge) {
    this.block4Tag71gReceivCharge = block4Tag71gReceivCharge;
    return this;
  }

   /**
   * Get block4Tag71gReceivCharge
   * @return block4Tag71gReceivCharge
  **/
  @Schema(description = "")
  public BigDecimal getBlock4Tag71gReceivCharge() {
    return block4Tag71gReceivCharge;
  }

  public void setBlock4Tag71gReceivCharge(BigDecimal block4Tag71gReceivCharge) {
    this.block4Tag71gReceivCharge = block4Tag71gReceivCharge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag70to71 block4Tag70to71 = (Block4Tag70to71) o;
    return Objects.equals(this.block4Tag70Nar1, block4Tag70to71.block4Tag70Nar1) &&
        Objects.equals(this.block4Tag70Nar2, block4Tag70to71.block4Tag70Nar2) &&
        Objects.equals(this.block4Tag70Nar3, block4Tag70to71.block4Tag70Nar3) &&
        Objects.equals(this.block4Tag70Nar4, block4Tag70to71.block4Tag70Nar4) &&
        Objects.equals(this.block4Tag71a, block4Tag70to71.block4Tag71a) &&
        Objects.equals(this.block4Tag71gCurrency, block4Tag70to71.block4Tag71gCurrency) &&
        Objects.equals(this.block4Tag71gReceivCharge, block4Tag70to71.block4Tag71gReceivCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag70Nar1, block4Tag70Nar2, block4Tag70Nar3, block4Tag70Nar4, block4Tag71a, block4Tag71gCurrency, block4Tag71gReceivCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag70to71 {\n");
    
    sb.append("    block4Tag70Nar1: ").append(toIndentedString(block4Tag70Nar1)).append("\n");
    sb.append("    block4Tag70Nar2: ").append(toIndentedString(block4Tag70Nar2)).append("\n");
    sb.append("    block4Tag70Nar3: ").append(toIndentedString(block4Tag70Nar3)).append("\n");
    sb.append("    block4Tag70Nar4: ").append(toIndentedString(block4Tag70Nar4)).append("\n");
    sb.append("    block4Tag71a: ").append(toIndentedString(block4Tag71a)).append("\n");
    sb.append("    block4Tag71gCurrency: ").append(toIndentedString(block4Tag71gCurrency)).append("\n");
    sb.append("    block4Tag71gReceivCharge: ").append(toIndentedString(block4Tag71gReceivCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
