/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag77
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag77 {
  @SerializedName("block4Tag77bCode")
  private String block4Tag77bCode = null;

  @SerializedName("block4Tag77bCountryCode")
  private String block4Tag77bCountryCode = null;

  @SerializedName("block4Tag77bNarrative")
  private String block4Tag77bNarrative = null;

  public Block4Tag77 block4Tag77bCode(String block4Tag77bCode) {
    this.block4Tag77bCode = block4Tag77bCode;
    return this;
  }

   /**
   * Get block4Tag77bCode
   * @return block4Tag77bCode
  **/
  @Schema(description = "")
  public String getBlock4Tag77bCode() {
    return block4Tag77bCode;
  }

  public void setBlock4Tag77bCode(String block4Tag77bCode) {
    this.block4Tag77bCode = block4Tag77bCode;
  }

  public Block4Tag77 block4Tag77bCountryCode(String block4Tag77bCountryCode) {
    this.block4Tag77bCountryCode = block4Tag77bCountryCode;
    return this;
  }

   /**
   * Get block4Tag77bCountryCode
   * @return block4Tag77bCountryCode
  **/
  @Schema(description = "")
  public String getBlock4Tag77bCountryCode() {
    return block4Tag77bCountryCode;
  }

  public void setBlock4Tag77bCountryCode(String block4Tag77bCountryCode) {
    this.block4Tag77bCountryCode = block4Tag77bCountryCode;
  }

  public Block4Tag77 block4Tag77bNarrative(String block4Tag77bNarrative) {
    this.block4Tag77bNarrative = block4Tag77bNarrative;
    return this;
  }

   /**
   * Get block4Tag77bNarrative
   * @return block4Tag77bNarrative
  **/
  @Schema(description = "")
  public String getBlock4Tag77bNarrative() {
    return block4Tag77bNarrative;
  }

  public void setBlock4Tag77bNarrative(String block4Tag77bNarrative) {
    this.block4Tag77bNarrative = block4Tag77bNarrative;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag77 block4Tag77 = (Block4Tag77) o;
    return Objects.equals(this.block4Tag77bCode, block4Tag77.block4Tag77bCode) &&
        Objects.equals(this.block4Tag77bCountryCode, block4Tag77.block4Tag77bCountryCode) &&
        Objects.equals(this.block4Tag77bNarrative, block4Tag77.block4Tag77bNarrative);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag77bCode, block4Tag77bCountryCode, block4Tag77bNarrative);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag77 {\n");
    
    sb.append("    block4Tag77bCode: ").append(toIndentedString(block4Tag77bCode)).append("\n");
    sb.append("    block4Tag77bCountryCode: ").append(toIndentedString(block4Tag77bCountryCode)).append("\n");
    sb.append("    block4Tag77bNarrative: ").append(toIndentedString(block4Tag77bNarrative)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
