/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag50
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag50 {
  @SerializedName("block4Tag50aAcct")
  private String block4Tag50aAcct = null;

  @SerializedName("block4Tag50aBic")
  private String block4Tag50aBic = null;

  @SerializedName("block4Tag50fNameAddr1")
  private String block4Tag50fNameAddr1 = null;

  @SerializedName("block4Tag50fNameAddr2")
  private String block4Tag50fNameAddr2 = null;

  @SerializedName("block4Tag50fNameAddr3")
  private String block4Tag50fNameAddr3 = null;

  @SerializedName("block4Tag50fNameAddr4")
  private String block4Tag50fNameAddr4 = null;

  @SerializedName("block4Tag50fNumber1")
  private String block4Tag50fNumber1 = null;

  @SerializedName("block4Tag50fNumber2")
  private String block4Tag50fNumber2 = null;

  @SerializedName("block4Tag50fNumber3")
  private String block4Tag50fNumber3 = null;

  @SerializedName("block4Tag50fNumber4")
  private String block4Tag50fNumber4 = null;

  @SerializedName("block4Tag50fPartyId")
  private String block4Tag50fPartyId = null;

  @SerializedName("block4Tag50kAccount")
  private String block4Tag50kAccount = null;

  @SerializedName("block4Tag50kNameAddr")
  private String block4Tag50kNameAddr = null;

  public Block4Tag50 block4Tag50aAcct(String block4Tag50aAcct) {
    this.block4Tag50aAcct = block4Tag50aAcct;
    return this;
  }

   /**
   * Get block4Tag50aAcct
   * @return block4Tag50aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag50aAcct() {
    return block4Tag50aAcct;
  }

  public void setBlock4Tag50aAcct(String block4Tag50aAcct) {
    this.block4Tag50aAcct = block4Tag50aAcct;
  }

  public Block4Tag50 block4Tag50aBic(String block4Tag50aBic) {
    this.block4Tag50aBic = block4Tag50aBic;
    return this;
  }

   /**
   * Get block4Tag50aBic
   * @return block4Tag50aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag50aBic() {
    return block4Tag50aBic;
  }

  public void setBlock4Tag50aBic(String block4Tag50aBic) {
    this.block4Tag50aBic = block4Tag50aBic;
  }

  public Block4Tag50 block4Tag50fNameAddr1(String block4Tag50fNameAddr1) {
    this.block4Tag50fNameAddr1 = block4Tag50fNameAddr1;
    return this;
  }

   /**
   * Get block4Tag50fNameAddr1
   * @return block4Tag50fNameAddr1
  **/
  @Schema(description = "")
  public String getBlock4Tag50fNameAddr1() {
    return block4Tag50fNameAddr1;
  }

  public void setBlock4Tag50fNameAddr1(String block4Tag50fNameAddr1) {
    this.block4Tag50fNameAddr1 = block4Tag50fNameAddr1;
  }

  public Block4Tag50 block4Tag50fNameAddr2(String block4Tag50fNameAddr2) {
    this.block4Tag50fNameAddr2 = block4Tag50fNameAddr2;
    return this;
  }

   /**
   * Get block4Tag50fNameAddr2
   * @return block4Tag50fNameAddr2
  **/
  @Schema(description = "")
  public String getBlock4Tag50fNameAddr2() {
    return block4Tag50fNameAddr2;
  }

  public void setBlock4Tag50fNameAddr2(String block4Tag50fNameAddr2) {
    this.block4Tag50fNameAddr2 = block4Tag50fNameAddr2;
  }

  public Block4Tag50 block4Tag50fNameAddr3(String block4Tag50fNameAddr3) {
    this.block4Tag50fNameAddr3 = block4Tag50fNameAddr3;
    return this;
  }

   /**
   * Get block4Tag50fNameAddr3
   * @return block4Tag50fNameAddr3
  **/
  @Schema(description = "")
  public String getBlock4Tag50fNameAddr3() {
    return block4Tag50fNameAddr3;
  }

  public void setBlock4Tag50fNameAddr3(String block4Tag50fNameAddr3) {
    this.block4Tag50fNameAddr3 = block4Tag50fNameAddr3;
  }

  public Block4Tag50 block4Tag50fNameAddr4(String block4Tag50fNameAddr4) {
    this.block4Tag50fNameAddr4 = block4Tag50fNameAddr4;
    return this;
  }

   /**
   * Get block4Tag50fNameAddr4
   * @return block4Tag50fNameAddr4
  **/
  @Schema(description = "")
  public String getBlock4Tag50fNameAddr4() {
    return block4Tag50fNameAddr4;
  }

  public void setBlock4Tag50fNameAddr4(String block4Tag50fNameAddr4) {
    this.block4Tag50fNameAddr4 = block4Tag50fNameAddr4;
  }

  public Block4Tag50 block4Tag50fNumber1(String block4Tag50fNumber1) {
    this.block4Tag50fNumber1 = block4Tag50fNumber1;
    return this;
  }

   /**
   * Get block4Tag50fNumber1
   * @return block4Tag50fNumber1
  **/
  @Schema(description = "")
  public String getBlock4Tag50fNumber1() {
    return block4Tag50fNumber1;
  }

  public void setBlock4Tag50fNumber1(String block4Tag50fNumber1) {
    this.block4Tag50fNumber1 = block4Tag50fNumber1;
  }

  public Block4Tag50 block4Tag50fNumber2(String block4Tag50fNumber2) {
    this.block4Tag50fNumber2 = block4Tag50fNumber2;
    return this;
  }

   /**
   * Get block4Tag50fNumber2
   * @return block4Tag50fNumber2
  **/
  @Schema(description = "")
  public String getBlock4Tag50fNumber2() {
    return block4Tag50fNumber2;
  }

  public void setBlock4Tag50fNumber2(String block4Tag50fNumber2) {
    this.block4Tag50fNumber2 = block4Tag50fNumber2;
  }

  public Block4Tag50 block4Tag50fNumber3(String block4Tag50fNumber3) {
    this.block4Tag50fNumber3 = block4Tag50fNumber3;
    return this;
  }

   /**
   * Get block4Tag50fNumber3
   * @return block4Tag50fNumber3
  **/
  @Schema(description = "")
  public String getBlock4Tag50fNumber3() {
    return block4Tag50fNumber3;
  }

  public void setBlock4Tag50fNumber3(String block4Tag50fNumber3) {
    this.block4Tag50fNumber3 = block4Tag50fNumber3;
  }

  public Block4Tag50 block4Tag50fNumber4(String block4Tag50fNumber4) {
    this.block4Tag50fNumber4 = block4Tag50fNumber4;
    return this;
  }

   /**
   * Get block4Tag50fNumber4
   * @return block4Tag50fNumber4
  **/
  @Schema(description = "")
  public String getBlock4Tag50fNumber4() {
    return block4Tag50fNumber4;
  }

  public void setBlock4Tag50fNumber4(String block4Tag50fNumber4) {
    this.block4Tag50fNumber4 = block4Tag50fNumber4;
  }

  public Block4Tag50 block4Tag50fPartyId(String block4Tag50fPartyId) {
    this.block4Tag50fPartyId = block4Tag50fPartyId;
    return this;
  }

   /**
   * Get block4Tag50fPartyId
   * @return block4Tag50fPartyId
  **/
  @Schema(description = "")
  public String getBlock4Tag50fPartyId() {
    return block4Tag50fPartyId;
  }

  public void setBlock4Tag50fPartyId(String block4Tag50fPartyId) {
    this.block4Tag50fPartyId = block4Tag50fPartyId;
  }

  public Block4Tag50 block4Tag50kAccount(String block4Tag50kAccount) {
    this.block4Tag50kAccount = block4Tag50kAccount;
    return this;
  }

   /**
   * Get block4Tag50kAccount
   * @return block4Tag50kAccount
  **/
  @Schema(description = "")
  public String getBlock4Tag50kAccount() {
    return block4Tag50kAccount;
  }

  public void setBlock4Tag50kAccount(String block4Tag50kAccount) {
    this.block4Tag50kAccount = block4Tag50kAccount;
  }

  public Block4Tag50 block4Tag50kNameAddr(String block4Tag50kNameAddr) {
    this.block4Tag50kNameAddr = block4Tag50kNameAddr;
    return this;
  }

   /**
   * Get block4Tag50kNameAddr
   * @return block4Tag50kNameAddr
  **/
  @Schema(description = "")
  public String getBlock4Tag50kNameAddr() {
    return block4Tag50kNameAddr;
  }

  public void setBlock4Tag50kNameAddr(String block4Tag50kNameAddr) {
    this.block4Tag50kNameAddr = block4Tag50kNameAddr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag50 block4Tag50 = (Block4Tag50) o;
    return Objects.equals(this.block4Tag50aAcct, block4Tag50.block4Tag50aAcct) &&
        Objects.equals(this.block4Tag50aBic, block4Tag50.block4Tag50aBic) &&
        Objects.equals(this.block4Tag50fNameAddr1, block4Tag50.block4Tag50fNameAddr1) &&
        Objects.equals(this.block4Tag50fNameAddr2, block4Tag50.block4Tag50fNameAddr2) &&
        Objects.equals(this.block4Tag50fNameAddr3, block4Tag50.block4Tag50fNameAddr3) &&
        Objects.equals(this.block4Tag50fNameAddr4, block4Tag50.block4Tag50fNameAddr4) &&
        Objects.equals(this.block4Tag50fNumber1, block4Tag50.block4Tag50fNumber1) &&
        Objects.equals(this.block4Tag50fNumber2, block4Tag50.block4Tag50fNumber2) &&
        Objects.equals(this.block4Tag50fNumber3, block4Tag50.block4Tag50fNumber3) &&
        Objects.equals(this.block4Tag50fNumber4, block4Tag50.block4Tag50fNumber4) &&
        Objects.equals(this.block4Tag50fPartyId, block4Tag50.block4Tag50fPartyId) &&
        Objects.equals(this.block4Tag50kAccount, block4Tag50.block4Tag50kAccount) &&
        Objects.equals(this.block4Tag50kNameAddr, block4Tag50.block4Tag50kNameAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag50aAcct, block4Tag50aBic, block4Tag50fNameAddr1, block4Tag50fNameAddr2, block4Tag50fNameAddr3, block4Tag50fNameAddr4, block4Tag50fNumber1, block4Tag50fNumber2, block4Tag50fNumber3, block4Tag50fNumber4, block4Tag50fPartyId, block4Tag50kAccount, block4Tag50kNameAddr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag50 {\n");
    
    sb.append("    block4Tag50aAcct: ").append(toIndentedString(block4Tag50aAcct)).append("\n");
    sb.append("    block4Tag50aBic: ").append(toIndentedString(block4Tag50aBic)).append("\n");
    sb.append("    block4Tag50fNameAddr1: ").append(toIndentedString(block4Tag50fNameAddr1)).append("\n");
    sb.append("    block4Tag50fNameAddr2: ").append(toIndentedString(block4Tag50fNameAddr2)).append("\n");
    sb.append("    block4Tag50fNameAddr3: ").append(toIndentedString(block4Tag50fNameAddr3)).append("\n");
    sb.append("    block4Tag50fNameAddr4: ").append(toIndentedString(block4Tag50fNameAddr4)).append("\n");
    sb.append("    block4Tag50fNumber1: ").append(toIndentedString(block4Tag50fNumber1)).append("\n");
    sb.append("    block4Tag50fNumber2: ").append(toIndentedString(block4Tag50fNumber2)).append("\n");
    sb.append("    block4Tag50fNumber3: ").append(toIndentedString(block4Tag50fNumber3)).append("\n");
    sb.append("    block4Tag50fNumber4: ").append(toIndentedString(block4Tag50fNumber4)).append("\n");
    sb.append("    block4Tag50fPartyId: ").append(toIndentedString(block4Tag50fPartyId)).append("\n");
    sb.append("    block4Tag50kAccount: ").append(toIndentedString(block4Tag50kAccount)).append("\n");
    sb.append("    block4Tag50kNameAddr: ").append(toIndentedString(block4Tag50kNameAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
