/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag59
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag59 {
  @SerializedName("block4Tag59Acct")
  private String block4Tag59Acct = null;

  @SerializedName("block4Tag59NameAddr")
  private String block4Tag59NameAddr = null;

  @SerializedName("block4Tag59aAcct")
  private String block4Tag59aAcct = null;

  @SerializedName("block4Tag59aBic")
  private String block4Tag59aBic = null;

  @SerializedName("block4Tag59fAcct")
  private String block4Tag59fAcct = null;

  @SerializedName("block4Tag59fNameAddr1")
  private String block4Tag59fNameAddr1 = null;

  @SerializedName("block4Tag59fNameAddr2")
  private String block4Tag59fNameAddr2 = null;

  @SerializedName("block4Tag59fNameAddr3")
  private String block4Tag59fNameAddr3 = null;

  @SerializedName("block4Tag59fNameAddr4")
  private String block4Tag59fNameAddr4 = null;

  @SerializedName("block4Tag59fNumber1")
  private String block4Tag59fNumber1 = null;

  @SerializedName("block4Tag59fNumber2")
  private String block4Tag59fNumber2 = null;

  @SerializedName("block4Tag59fNumber3")
  private String block4Tag59fNumber3 = null;

  @SerializedName("block4Tag59fNumber4")
  private String block4Tag59fNumber4 = null;

  public Block4Tag59 block4Tag59Acct(String block4Tag59Acct) {
    this.block4Tag59Acct = block4Tag59Acct;
    return this;
  }

   /**
   * Get block4Tag59Acct
   * @return block4Tag59Acct
  **/
  @Schema(description = "")
  public String getBlock4Tag59Acct() {
    return block4Tag59Acct;
  }

  public void setBlock4Tag59Acct(String block4Tag59Acct) {
    this.block4Tag59Acct = block4Tag59Acct;
  }

  public Block4Tag59 block4Tag59NameAddr(String block4Tag59NameAddr) {
    this.block4Tag59NameAddr = block4Tag59NameAddr;
    return this;
  }

   /**
   * Get block4Tag59NameAddr
   * @return block4Tag59NameAddr
  **/
  @Schema(description = "")
  public String getBlock4Tag59NameAddr() {
    return block4Tag59NameAddr;
  }

  public void setBlock4Tag59NameAddr(String block4Tag59NameAddr) {
    this.block4Tag59NameAddr = block4Tag59NameAddr;
  }

  public Block4Tag59 block4Tag59aAcct(String block4Tag59aAcct) {
    this.block4Tag59aAcct = block4Tag59aAcct;
    return this;
  }

   /**
   * Get block4Tag59aAcct
   * @return block4Tag59aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag59aAcct() {
    return block4Tag59aAcct;
  }

  public void setBlock4Tag59aAcct(String block4Tag59aAcct) {
    this.block4Tag59aAcct = block4Tag59aAcct;
  }

  public Block4Tag59 block4Tag59aBic(String block4Tag59aBic) {
    this.block4Tag59aBic = block4Tag59aBic;
    return this;
  }

   /**
   * Get block4Tag59aBic
   * @return block4Tag59aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag59aBic() {
    return block4Tag59aBic;
  }

  public void setBlock4Tag59aBic(String block4Tag59aBic) {
    this.block4Tag59aBic = block4Tag59aBic;
  }

  public Block4Tag59 block4Tag59fAcct(String block4Tag59fAcct) {
    this.block4Tag59fAcct = block4Tag59fAcct;
    return this;
  }

   /**
   * Get block4Tag59fAcct
   * @return block4Tag59fAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag59fAcct() {
    return block4Tag59fAcct;
  }

  public void setBlock4Tag59fAcct(String block4Tag59fAcct) {
    this.block4Tag59fAcct = block4Tag59fAcct;
  }

  public Block4Tag59 block4Tag59fNameAddr1(String block4Tag59fNameAddr1) {
    this.block4Tag59fNameAddr1 = block4Tag59fNameAddr1;
    return this;
  }

   /**
   * Get block4Tag59fNameAddr1
   * @return block4Tag59fNameAddr1
  **/
  @Schema(description = "")
  public String getBlock4Tag59fNameAddr1() {
    return block4Tag59fNameAddr1;
  }

  public void setBlock4Tag59fNameAddr1(String block4Tag59fNameAddr1) {
    this.block4Tag59fNameAddr1 = block4Tag59fNameAddr1;
  }

  public Block4Tag59 block4Tag59fNameAddr2(String block4Tag59fNameAddr2) {
    this.block4Tag59fNameAddr2 = block4Tag59fNameAddr2;
    return this;
  }

   /**
   * Get block4Tag59fNameAddr2
   * @return block4Tag59fNameAddr2
  **/
  @Schema(description = "")
  public String getBlock4Tag59fNameAddr2() {
    return block4Tag59fNameAddr2;
  }

  public void setBlock4Tag59fNameAddr2(String block4Tag59fNameAddr2) {
    this.block4Tag59fNameAddr2 = block4Tag59fNameAddr2;
  }

  public Block4Tag59 block4Tag59fNameAddr3(String block4Tag59fNameAddr3) {
    this.block4Tag59fNameAddr3 = block4Tag59fNameAddr3;
    return this;
  }

   /**
   * Get block4Tag59fNameAddr3
   * @return block4Tag59fNameAddr3
  **/
  @Schema(description = "")
  public String getBlock4Tag59fNameAddr3() {
    return block4Tag59fNameAddr3;
  }

  public void setBlock4Tag59fNameAddr3(String block4Tag59fNameAddr3) {
    this.block4Tag59fNameAddr3 = block4Tag59fNameAddr3;
  }

  public Block4Tag59 block4Tag59fNameAddr4(String block4Tag59fNameAddr4) {
    this.block4Tag59fNameAddr4 = block4Tag59fNameAddr4;
    return this;
  }

   /**
   * Get block4Tag59fNameAddr4
   * @return block4Tag59fNameAddr4
  **/
  @Schema(description = "")
  public String getBlock4Tag59fNameAddr4() {
    return block4Tag59fNameAddr4;
  }

  public void setBlock4Tag59fNameAddr4(String block4Tag59fNameAddr4) {
    this.block4Tag59fNameAddr4 = block4Tag59fNameAddr4;
  }

  public Block4Tag59 block4Tag59fNumber1(String block4Tag59fNumber1) {
    this.block4Tag59fNumber1 = block4Tag59fNumber1;
    return this;
  }

   /**
   * Get block4Tag59fNumber1
   * @return block4Tag59fNumber1
  **/
  @Schema(description = "")
  public String getBlock4Tag59fNumber1() {
    return block4Tag59fNumber1;
  }

  public void setBlock4Tag59fNumber1(String block4Tag59fNumber1) {
    this.block4Tag59fNumber1 = block4Tag59fNumber1;
  }

  public Block4Tag59 block4Tag59fNumber2(String block4Tag59fNumber2) {
    this.block4Tag59fNumber2 = block4Tag59fNumber2;
    return this;
  }

   /**
   * Get block4Tag59fNumber2
   * @return block4Tag59fNumber2
  **/
  @Schema(description = "")
  public String getBlock4Tag59fNumber2() {
    return block4Tag59fNumber2;
  }

  public void setBlock4Tag59fNumber2(String block4Tag59fNumber2) {
    this.block4Tag59fNumber2 = block4Tag59fNumber2;
  }

  public Block4Tag59 block4Tag59fNumber3(String block4Tag59fNumber3) {
    this.block4Tag59fNumber3 = block4Tag59fNumber3;
    return this;
  }

   /**
   * Get block4Tag59fNumber3
   * @return block4Tag59fNumber3
  **/
  @Schema(description = "")
  public String getBlock4Tag59fNumber3() {
    return block4Tag59fNumber3;
  }

  public void setBlock4Tag59fNumber3(String block4Tag59fNumber3) {
    this.block4Tag59fNumber3 = block4Tag59fNumber3;
  }

  public Block4Tag59 block4Tag59fNumber4(String block4Tag59fNumber4) {
    this.block4Tag59fNumber4 = block4Tag59fNumber4;
    return this;
  }

   /**
   * Get block4Tag59fNumber4
   * @return block4Tag59fNumber4
  **/
  @Schema(description = "")
  public String getBlock4Tag59fNumber4() {
    return block4Tag59fNumber4;
  }

  public void setBlock4Tag59fNumber4(String block4Tag59fNumber4) {
    this.block4Tag59fNumber4 = block4Tag59fNumber4;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag59 block4Tag59 = (Block4Tag59) o;
    return Objects.equals(this.block4Tag59Acct, block4Tag59.block4Tag59Acct) &&
        Objects.equals(this.block4Tag59NameAddr, block4Tag59.block4Tag59NameAddr) &&
        Objects.equals(this.block4Tag59aAcct, block4Tag59.block4Tag59aAcct) &&
        Objects.equals(this.block4Tag59aBic, block4Tag59.block4Tag59aBic) &&
        Objects.equals(this.block4Tag59fAcct, block4Tag59.block4Tag59fAcct) &&
        Objects.equals(this.block4Tag59fNameAddr1, block4Tag59.block4Tag59fNameAddr1) &&
        Objects.equals(this.block4Tag59fNameAddr2, block4Tag59.block4Tag59fNameAddr2) &&
        Objects.equals(this.block4Tag59fNameAddr3, block4Tag59.block4Tag59fNameAddr3) &&
        Objects.equals(this.block4Tag59fNameAddr4, block4Tag59.block4Tag59fNameAddr4) &&
        Objects.equals(this.block4Tag59fNumber1, block4Tag59.block4Tag59fNumber1) &&
        Objects.equals(this.block4Tag59fNumber2, block4Tag59.block4Tag59fNumber2) &&
        Objects.equals(this.block4Tag59fNumber3, block4Tag59.block4Tag59fNumber3) &&
        Objects.equals(this.block4Tag59fNumber4, block4Tag59.block4Tag59fNumber4);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag59Acct, block4Tag59NameAddr, block4Tag59aAcct, block4Tag59aBic, block4Tag59fAcct, block4Tag59fNameAddr1, block4Tag59fNameAddr2, block4Tag59fNameAddr3, block4Tag59fNameAddr4, block4Tag59fNumber1, block4Tag59fNumber2, block4Tag59fNumber3, block4Tag59fNumber4);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag59 {\n");
    
    sb.append("    block4Tag59Acct: ").append(toIndentedString(block4Tag59Acct)).append("\n");
    sb.append("    block4Tag59NameAddr: ").append(toIndentedString(block4Tag59NameAddr)).append("\n");
    sb.append("    block4Tag59aAcct: ").append(toIndentedString(block4Tag59aAcct)).append("\n");
    sb.append("    block4Tag59aBic: ").append(toIndentedString(block4Tag59aBic)).append("\n");
    sb.append("    block4Tag59fAcct: ").append(toIndentedString(block4Tag59fAcct)).append("\n");
    sb.append("    block4Tag59fNameAddr1: ").append(toIndentedString(block4Tag59fNameAddr1)).append("\n");
    sb.append("    block4Tag59fNameAddr2: ").append(toIndentedString(block4Tag59fNameAddr2)).append("\n");
    sb.append("    block4Tag59fNameAddr3: ").append(toIndentedString(block4Tag59fNameAddr3)).append("\n");
    sb.append("    block4Tag59fNameAddr4: ").append(toIndentedString(block4Tag59fNameAddr4)).append("\n");
    sb.append("    block4Tag59fNumber1: ").append(toIndentedString(block4Tag59fNumber1)).append("\n");
    sb.append("    block4Tag59fNumber2: ").append(toIndentedString(block4Tag59fNumber2)).append("\n");
    sb.append("    block4Tag59fNumber3: ").append(toIndentedString(block4Tag59fNumber3)).append("\n");
    sb.append("    block4Tag59fNumber4: ").append(toIndentedString(block4Tag59fNumber4)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
