/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag57
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag57 {
  @SerializedName("block4Tag57aAcct")
  private String block4Tag57aAcct = null;

  @SerializedName("block4Tag57aBic")
  private String block4Tag57aBic = null;

  @SerializedName("block4Tag57aDcmark")
  private String block4Tag57aDcmark = null;

  @SerializedName("block4Tag57bAcct")
  private String block4Tag57bAcct = null;

  @SerializedName("block4Tag57bDcmark")
  private String block4Tag57bDcmark = null;

  @SerializedName("block4Tag57bLocation")
  private String block4Tag57bLocation = null;

  @SerializedName("block4Tag57dAcct")
  private String block4Tag57dAcct = null;

  @SerializedName("block4Tag57dDcmark")
  private String block4Tag57dDcmark = null;

  @SerializedName("block4Tag57dNameAddr")
  private String block4Tag57dNameAddr = null;

  public Block4Tag57 block4Tag57aAcct(String block4Tag57aAcct) {
    this.block4Tag57aAcct = block4Tag57aAcct;
    return this;
  }

   /**
   * Get block4Tag57aAcct
   * @return block4Tag57aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag57aAcct() {
    return block4Tag57aAcct;
  }

  public void setBlock4Tag57aAcct(String block4Tag57aAcct) {
    this.block4Tag57aAcct = block4Tag57aAcct;
  }

  public Block4Tag57 block4Tag57aBic(String block4Tag57aBic) {
    this.block4Tag57aBic = block4Tag57aBic;
    return this;
  }

   /**
   * Get block4Tag57aBic
   * @return block4Tag57aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag57aBic() {
    return block4Tag57aBic;
  }

  public void setBlock4Tag57aBic(String block4Tag57aBic) {
    this.block4Tag57aBic = block4Tag57aBic;
  }

  public Block4Tag57 block4Tag57aDcmark(String block4Tag57aDcmark) {
    this.block4Tag57aDcmark = block4Tag57aDcmark;
    return this;
  }

   /**
   * Get block4Tag57aDcmark
   * @return block4Tag57aDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag57aDcmark() {
    return block4Tag57aDcmark;
  }

  public void setBlock4Tag57aDcmark(String block4Tag57aDcmark) {
    this.block4Tag57aDcmark = block4Tag57aDcmark;
  }

  public Block4Tag57 block4Tag57bAcct(String block4Tag57bAcct) {
    this.block4Tag57bAcct = block4Tag57bAcct;
    return this;
  }

   /**
   * Get block4Tag57bAcct
   * @return block4Tag57bAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag57bAcct() {
    return block4Tag57bAcct;
  }

  public void setBlock4Tag57bAcct(String block4Tag57bAcct) {
    this.block4Tag57bAcct = block4Tag57bAcct;
  }

  public Block4Tag57 block4Tag57bDcmark(String block4Tag57bDcmark) {
    this.block4Tag57bDcmark = block4Tag57bDcmark;
    return this;
  }

   /**
   * Get block4Tag57bDcmark
   * @return block4Tag57bDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag57bDcmark() {
    return block4Tag57bDcmark;
  }

  public void setBlock4Tag57bDcmark(String block4Tag57bDcmark) {
    this.block4Tag57bDcmark = block4Tag57bDcmark;
  }

  public Block4Tag57 block4Tag57bLocation(String block4Tag57bLocation) {
    this.block4Tag57bLocation = block4Tag57bLocation;
    return this;
  }

   /**
   * Get block4Tag57bLocation
   * @return block4Tag57bLocation
  **/
  @Schema(description = "")
  public String getBlock4Tag57bLocation() {
    return block4Tag57bLocation;
  }

  public void setBlock4Tag57bLocation(String block4Tag57bLocation) {
    this.block4Tag57bLocation = block4Tag57bLocation;
  }

  public Block4Tag57 block4Tag57dAcct(String block4Tag57dAcct) {
    this.block4Tag57dAcct = block4Tag57dAcct;
    return this;
  }

   /**
   * Get block4Tag57dAcct
   * @return block4Tag57dAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag57dAcct() {
    return block4Tag57dAcct;
  }

  public void setBlock4Tag57dAcct(String block4Tag57dAcct) {
    this.block4Tag57dAcct = block4Tag57dAcct;
  }

  public Block4Tag57 block4Tag57dDcmark(String block4Tag57dDcmark) {
    this.block4Tag57dDcmark = block4Tag57dDcmark;
    return this;
  }

   /**
   * Get block4Tag57dDcmark
   * @return block4Tag57dDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag57dDcmark() {
    return block4Tag57dDcmark;
  }

  public void setBlock4Tag57dDcmark(String block4Tag57dDcmark) {
    this.block4Tag57dDcmark = block4Tag57dDcmark;
  }

  public Block4Tag57 block4Tag57dNameAddr(String block4Tag57dNameAddr) {
    this.block4Tag57dNameAddr = block4Tag57dNameAddr;
    return this;
  }

   /**
   * Get block4Tag57dNameAddr
   * @return block4Tag57dNameAddr
  **/
  @Schema(description = "")
  public String getBlock4Tag57dNameAddr() {
    return block4Tag57dNameAddr;
  }

  public void setBlock4Tag57dNameAddr(String block4Tag57dNameAddr) {
    this.block4Tag57dNameAddr = block4Tag57dNameAddr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag57 block4Tag57 = (Block4Tag57) o;
    return Objects.equals(this.block4Tag57aAcct, block4Tag57.block4Tag57aAcct) &&
        Objects.equals(this.block4Tag57aBic, block4Tag57.block4Tag57aBic) &&
        Objects.equals(this.block4Tag57aDcmark, block4Tag57.block4Tag57aDcmark) &&
        Objects.equals(this.block4Tag57bAcct, block4Tag57.block4Tag57bAcct) &&
        Objects.equals(this.block4Tag57bDcmark, block4Tag57.block4Tag57bDcmark) &&
        Objects.equals(this.block4Tag57bLocation, block4Tag57.block4Tag57bLocation) &&
        Objects.equals(this.block4Tag57dAcct, block4Tag57.block4Tag57dAcct) &&
        Objects.equals(this.block4Tag57dDcmark, block4Tag57.block4Tag57dDcmark) &&
        Objects.equals(this.block4Tag57dNameAddr, block4Tag57.block4Tag57dNameAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag57aAcct, block4Tag57aBic, block4Tag57aDcmark, block4Tag57bAcct, block4Tag57bDcmark, block4Tag57bLocation, block4Tag57dAcct, block4Tag57dDcmark, block4Tag57dNameAddr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag57 {\n");
    
    sb.append("    block4Tag57aAcct: ").append(toIndentedString(block4Tag57aAcct)).append("\n");
    sb.append("    block4Tag57aBic: ").append(toIndentedString(block4Tag57aBic)).append("\n");
    sb.append("    block4Tag57aDcmark: ").append(toIndentedString(block4Tag57aDcmark)).append("\n");
    sb.append("    block4Tag57bAcct: ").append(toIndentedString(block4Tag57bAcct)).append("\n");
    sb.append("    block4Tag57bDcmark: ").append(toIndentedString(block4Tag57bDcmark)).append("\n");
    sb.append("    block4Tag57bLocation: ").append(toIndentedString(block4Tag57bLocation)).append("\n");
    sb.append("    block4Tag57dAcct: ").append(toIndentedString(block4Tag57dAcct)).append("\n");
    sb.append("    block4Tag57dDcmark: ").append(toIndentedString(block4Tag57dDcmark)).append("\n");
    sb.append("    block4Tag57dNameAddr: ").append(toIndentedString(block4Tag57dNameAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
