/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag53
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag53 {
  @SerializedName("block4Tag53aAcct")
  private String block4Tag53aAcct = null;

  @SerializedName("block4Tag53aBic")
  private String block4Tag53aBic = null;

  @SerializedName("block4Tag53aDcmark")
  private String block4Tag53aDcmark = null;

  @SerializedName("block4Tag53bAcct")
  private String block4Tag53bAcct = null;

  @SerializedName("block4Tag53bDcmark")
  private String block4Tag53bDcmark = null;

  @SerializedName("block4Tag53bLocation")
  private String block4Tag53bLocation = null;

  @SerializedName("block4Tag53dAcct")
  private String block4Tag53dAcct = null;

  @SerializedName("block4Tag53dDcmark")
  private String block4Tag53dDcmark = null;

  @SerializedName("block4Tag53dNameAddr")
  private String block4Tag53dNameAddr = null;

  public Block4Tag53 block4Tag53aAcct(String block4Tag53aAcct) {
    this.block4Tag53aAcct = block4Tag53aAcct;
    return this;
  }

   /**
   * Get block4Tag53aAcct
   * @return block4Tag53aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag53aAcct() {
    return block4Tag53aAcct;
  }

  public void setBlock4Tag53aAcct(String block4Tag53aAcct) {
    this.block4Tag53aAcct = block4Tag53aAcct;
  }

  public Block4Tag53 block4Tag53aBic(String block4Tag53aBic) {
    this.block4Tag53aBic = block4Tag53aBic;
    return this;
  }

   /**
   * Get block4Tag53aBic
   * @return block4Tag53aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag53aBic() {
    return block4Tag53aBic;
  }

  public void setBlock4Tag53aBic(String block4Tag53aBic) {
    this.block4Tag53aBic = block4Tag53aBic;
  }

  public Block4Tag53 block4Tag53aDcmark(String block4Tag53aDcmark) {
    this.block4Tag53aDcmark = block4Tag53aDcmark;
    return this;
  }

   /**
   * Get block4Tag53aDcmark
   * @return block4Tag53aDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag53aDcmark() {
    return block4Tag53aDcmark;
  }

  public void setBlock4Tag53aDcmark(String block4Tag53aDcmark) {
    this.block4Tag53aDcmark = block4Tag53aDcmark;
  }

  public Block4Tag53 block4Tag53bAcct(String block4Tag53bAcct) {
    this.block4Tag53bAcct = block4Tag53bAcct;
    return this;
  }

   /**
   * Get block4Tag53bAcct
   * @return block4Tag53bAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag53bAcct() {
    return block4Tag53bAcct;
  }

  public void setBlock4Tag53bAcct(String block4Tag53bAcct) {
    this.block4Tag53bAcct = block4Tag53bAcct;
  }

  public Block4Tag53 block4Tag53bDcmark(String block4Tag53bDcmark) {
    this.block4Tag53bDcmark = block4Tag53bDcmark;
    return this;
  }

   /**
   * Get block4Tag53bDcmark
   * @return block4Tag53bDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag53bDcmark() {
    return block4Tag53bDcmark;
  }

  public void setBlock4Tag53bDcmark(String block4Tag53bDcmark) {
    this.block4Tag53bDcmark = block4Tag53bDcmark;
  }

  public Block4Tag53 block4Tag53bLocation(String block4Tag53bLocation) {
    this.block4Tag53bLocation = block4Tag53bLocation;
    return this;
  }

   /**
   * Get block4Tag53bLocation
   * @return block4Tag53bLocation
  **/
  @Schema(description = "")
  public String getBlock4Tag53bLocation() {
    return block4Tag53bLocation;
  }

  public void setBlock4Tag53bLocation(String block4Tag53bLocation) {
    this.block4Tag53bLocation = block4Tag53bLocation;
  }

  public Block4Tag53 block4Tag53dAcct(String block4Tag53dAcct) {
    this.block4Tag53dAcct = block4Tag53dAcct;
    return this;
  }

   /**
   * Get block4Tag53dAcct
   * @return block4Tag53dAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag53dAcct() {
    return block4Tag53dAcct;
  }

  public void setBlock4Tag53dAcct(String block4Tag53dAcct) {
    this.block4Tag53dAcct = block4Tag53dAcct;
  }

  public Block4Tag53 block4Tag53dDcmark(String block4Tag53dDcmark) {
    this.block4Tag53dDcmark = block4Tag53dDcmark;
    return this;
  }

   /**
   * Get block4Tag53dDcmark
   * @return block4Tag53dDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag53dDcmark() {
    return block4Tag53dDcmark;
  }

  public void setBlock4Tag53dDcmark(String block4Tag53dDcmark) {
    this.block4Tag53dDcmark = block4Tag53dDcmark;
  }

  public Block4Tag53 block4Tag53dNameAddr(String block4Tag53dNameAddr) {
    this.block4Tag53dNameAddr = block4Tag53dNameAddr;
    return this;
  }

   /**
   * Get block4Tag53dNameAddr
   * @return block4Tag53dNameAddr
  **/
  @Schema(description = "")
  public String getBlock4Tag53dNameAddr() {
    return block4Tag53dNameAddr;
  }

  public void setBlock4Tag53dNameAddr(String block4Tag53dNameAddr) {
    this.block4Tag53dNameAddr = block4Tag53dNameAddr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag53 block4Tag53 = (Block4Tag53) o;
    return Objects.equals(this.block4Tag53aAcct, block4Tag53.block4Tag53aAcct) &&
        Objects.equals(this.block4Tag53aBic, block4Tag53.block4Tag53aBic) &&
        Objects.equals(this.block4Tag53aDcmark, block4Tag53.block4Tag53aDcmark) &&
        Objects.equals(this.block4Tag53bAcct, block4Tag53.block4Tag53bAcct) &&
        Objects.equals(this.block4Tag53bDcmark, block4Tag53.block4Tag53bDcmark) &&
        Objects.equals(this.block4Tag53bLocation, block4Tag53.block4Tag53bLocation) &&
        Objects.equals(this.block4Tag53dAcct, block4Tag53.block4Tag53dAcct) &&
        Objects.equals(this.block4Tag53dDcmark, block4Tag53.block4Tag53dDcmark) &&
        Objects.equals(this.block4Tag53dNameAddr, block4Tag53.block4Tag53dNameAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag53aAcct, block4Tag53aBic, block4Tag53aDcmark, block4Tag53bAcct, block4Tag53bDcmark, block4Tag53bLocation, block4Tag53dAcct, block4Tag53dDcmark, block4Tag53dNameAddr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag53 {\n");
    
    sb.append("    block4Tag53aAcct: ").append(toIndentedString(block4Tag53aAcct)).append("\n");
    sb.append("    block4Tag53aBic: ").append(toIndentedString(block4Tag53aBic)).append("\n");
    sb.append("    block4Tag53aDcmark: ").append(toIndentedString(block4Tag53aDcmark)).append("\n");
    sb.append("    block4Tag53bAcct: ").append(toIndentedString(block4Tag53bAcct)).append("\n");
    sb.append("    block4Tag53bDcmark: ").append(toIndentedString(block4Tag53bDcmark)).append("\n");
    sb.append("    block4Tag53bLocation: ").append(toIndentedString(block4Tag53bLocation)).append("\n");
    sb.append("    block4Tag53dAcct: ").append(toIndentedString(block4Tag53dAcct)).append("\n");
    sb.append("    block4Tag53dDcmark: ").append(toIndentedString(block4Tag53dDcmark)).append("\n");
    sb.append("    block4Tag53dNameAddr: ").append(toIndentedString(block4Tag53dNameAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
