/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag54
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag54 {
  @SerializedName("block4Tag54aAcct")
  private String block4Tag54aAcct = null;

  @SerializedName("block4Tag54aBic")
  private String block4Tag54aBic = null;

  @SerializedName("block4Tag54aDcmark")
  private String block4Tag54aDcmark = null;

  @SerializedName("block4Tag54bAcct")
  private String block4Tag54bAcct = null;

  @SerializedName("block4Tag54bDcmark")
  private String block4Tag54bDcmark = null;

  @SerializedName("block4Tag54bLocation")
  private String block4Tag54bLocation = null;

  @SerializedName("block4Tag54dAcct")
  private String block4Tag54dAcct = null;

  @SerializedName("block4Tag54dDcmark")
  private String block4Tag54dDcmark = null;

  @SerializedName("block4Tag54dNameAddr")
  private String block4Tag54dNameAddr = null;

  public Block4Tag54 block4Tag54aAcct(String block4Tag54aAcct) {
    this.block4Tag54aAcct = block4Tag54aAcct;
    return this;
  }

   /**
   * Get block4Tag54aAcct
   * @return block4Tag54aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag54aAcct() {
    return block4Tag54aAcct;
  }

  public void setBlock4Tag54aAcct(String block4Tag54aAcct) {
    this.block4Tag54aAcct = block4Tag54aAcct;
  }

  public Block4Tag54 block4Tag54aBic(String block4Tag54aBic) {
    this.block4Tag54aBic = block4Tag54aBic;
    return this;
  }

   /**
   * Get block4Tag54aBic
   * @return block4Tag54aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag54aBic() {
    return block4Tag54aBic;
  }

  public void setBlock4Tag54aBic(String block4Tag54aBic) {
    this.block4Tag54aBic = block4Tag54aBic;
  }

  public Block4Tag54 block4Tag54aDcmark(String block4Tag54aDcmark) {
    this.block4Tag54aDcmark = block4Tag54aDcmark;
    return this;
  }

   /**
   * Get block4Tag54aDcmark
   * @return block4Tag54aDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag54aDcmark() {
    return block4Tag54aDcmark;
  }

  public void setBlock4Tag54aDcmark(String block4Tag54aDcmark) {
    this.block4Tag54aDcmark = block4Tag54aDcmark;
  }

  public Block4Tag54 block4Tag54bAcct(String block4Tag54bAcct) {
    this.block4Tag54bAcct = block4Tag54bAcct;
    return this;
  }

   /**
   * Get block4Tag54bAcct
   * @return block4Tag54bAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag54bAcct() {
    return block4Tag54bAcct;
  }

  public void setBlock4Tag54bAcct(String block4Tag54bAcct) {
    this.block4Tag54bAcct = block4Tag54bAcct;
  }

  public Block4Tag54 block4Tag54bDcmark(String block4Tag54bDcmark) {
    this.block4Tag54bDcmark = block4Tag54bDcmark;
    return this;
  }

   /**
   * Get block4Tag54bDcmark
   * @return block4Tag54bDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag54bDcmark() {
    return block4Tag54bDcmark;
  }

  public void setBlock4Tag54bDcmark(String block4Tag54bDcmark) {
    this.block4Tag54bDcmark = block4Tag54bDcmark;
  }

  public Block4Tag54 block4Tag54bLocation(String block4Tag54bLocation) {
    this.block4Tag54bLocation = block4Tag54bLocation;
    return this;
  }

   /**
   * Get block4Tag54bLocation
   * @return block4Tag54bLocation
  **/
  @Schema(description = "")
  public String getBlock4Tag54bLocation() {
    return block4Tag54bLocation;
  }

  public void setBlock4Tag54bLocation(String block4Tag54bLocation) {
    this.block4Tag54bLocation = block4Tag54bLocation;
  }

  public Block4Tag54 block4Tag54dAcct(String block4Tag54dAcct) {
    this.block4Tag54dAcct = block4Tag54dAcct;
    return this;
  }

   /**
   * Get block4Tag54dAcct
   * @return block4Tag54dAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag54dAcct() {
    return block4Tag54dAcct;
  }

  public void setBlock4Tag54dAcct(String block4Tag54dAcct) {
    this.block4Tag54dAcct = block4Tag54dAcct;
  }

  public Block4Tag54 block4Tag54dDcmark(String block4Tag54dDcmark) {
    this.block4Tag54dDcmark = block4Tag54dDcmark;
    return this;
  }

   /**
   * Get block4Tag54dDcmark
   * @return block4Tag54dDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag54dDcmark() {
    return block4Tag54dDcmark;
  }

  public void setBlock4Tag54dDcmark(String block4Tag54dDcmark) {
    this.block4Tag54dDcmark = block4Tag54dDcmark;
  }

  public Block4Tag54 block4Tag54dNameAddr(String block4Tag54dNameAddr) {
    this.block4Tag54dNameAddr = block4Tag54dNameAddr;
    return this;
  }

   /**
   * Get block4Tag54dNameAddr
   * @return block4Tag54dNameAddr
  **/
  @Schema(description = "")
  public String getBlock4Tag54dNameAddr() {
    return block4Tag54dNameAddr;
  }

  public void setBlock4Tag54dNameAddr(String block4Tag54dNameAddr) {
    this.block4Tag54dNameAddr = block4Tag54dNameAddr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag54 block4Tag54 = (Block4Tag54) o;
    return Objects.equals(this.block4Tag54aAcct, block4Tag54.block4Tag54aAcct) &&
        Objects.equals(this.block4Tag54aBic, block4Tag54.block4Tag54aBic) &&
        Objects.equals(this.block4Tag54aDcmark, block4Tag54.block4Tag54aDcmark) &&
        Objects.equals(this.block4Tag54bAcct, block4Tag54.block4Tag54bAcct) &&
        Objects.equals(this.block4Tag54bDcmark, block4Tag54.block4Tag54bDcmark) &&
        Objects.equals(this.block4Tag54bLocation, block4Tag54.block4Tag54bLocation) &&
        Objects.equals(this.block4Tag54dAcct, block4Tag54.block4Tag54dAcct) &&
        Objects.equals(this.block4Tag54dDcmark, block4Tag54.block4Tag54dDcmark) &&
        Objects.equals(this.block4Tag54dNameAddr, block4Tag54.block4Tag54dNameAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag54aAcct, block4Tag54aBic, block4Tag54aDcmark, block4Tag54bAcct, block4Tag54bDcmark, block4Tag54bLocation, block4Tag54dAcct, block4Tag54dDcmark, block4Tag54dNameAddr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag54 {\n");
    
    sb.append("    block4Tag54aAcct: ").append(toIndentedString(block4Tag54aAcct)).append("\n");
    sb.append("    block4Tag54aBic: ").append(toIndentedString(block4Tag54aBic)).append("\n");
    sb.append("    block4Tag54aDcmark: ").append(toIndentedString(block4Tag54aDcmark)).append("\n");
    sb.append("    block4Tag54bAcct: ").append(toIndentedString(block4Tag54bAcct)).append("\n");
    sb.append("    block4Tag54bDcmark: ").append(toIndentedString(block4Tag54bDcmark)).append("\n");
    sb.append("    block4Tag54bLocation: ").append(toIndentedString(block4Tag54bLocation)).append("\n");
    sb.append("    block4Tag54dAcct: ").append(toIndentedString(block4Tag54dAcct)).append("\n");
    sb.append("    block4Tag54dDcmark: ").append(toIndentedString(block4Tag54dDcmark)).append("\n");
    sb.append("    block4Tag54dNameAddr: ").append(toIndentedString(block4Tag54dNameAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
