/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Block4Tag55
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Block4Tag55 {
  @SerializedName("block4Tag55aAcct")
  private String block4Tag55aAcct = null;

  @SerializedName("block4Tag55aBic")
  private String block4Tag55aBic = null;

  @SerializedName("block4Tag55aDcmark")
  private String block4Tag55aDcmark = null;

  @SerializedName("block4Tag55bAcct")
  private String block4Tag55bAcct = null;

  @SerializedName("block4Tag55bDcmark")
  private String block4Tag55bDcmark = null;

  @SerializedName("block4Tag55bLocation")
  private String block4Tag55bLocation = null;

  @SerializedName("block4Tag55dAcct")
  private String block4Tag55dAcct = null;

  @SerializedName("block4Tag55dDcmark")
  private String block4Tag55dDcmark = null;

  @SerializedName("block4Tag55dNameAddr")
  private String block4Tag55dNameAddr = null;

  public Block4Tag55 block4Tag55aAcct(String block4Tag55aAcct) {
    this.block4Tag55aAcct = block4Tag55aAcct;
    return this;
  }

   /**
   * Get block4Tag55aAcct
   * @return block4Tag55aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag55aAcct() {
    return block4Tag55aAcct;
  }

  public void setBlock4Tag55aAcct(String block4Tag55aAcct) {
    this.block4Tag55aAcct = block4Tag55aAcct;
  }

  public Block4Tag55 block4Tag55aBic(String block4Tag55aBic) {
    this.block4Tag55aBic = block4Tag55aBic;
    return this;
  }

   /**
   * Get block4Tag55aBic
   * @return block4Tag55aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag55aBic() {
    return block4Tag55aBic;
  }

  public void setBlock4Tag55aBic(String block4Tag55aBic) {
    this.block4Tag55aBic = block4Tag55aBic;
  }

  public Block4Tag55 block4Tag55aDcmark(String block4Tag55aDcmark) {
    this.block4Tag55aDcmark = block4Tag55aDcmark;
    return this;
  }

   /**
   * Get block4Tag55aDcmark
   * @return block4Tag55aDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag55aDcmark() {
    return block4Tag55aDcmark;
  }

  public void setBlock4Tag55aDcmark(String block4Tag55aDcmark) {
    this.block4Tag55aDcmark = block4Tag55aDcmark;
  }

  public Block4Tag55 block4Tag55bAcct(String block4Tag55bAcct) {
    this.block4Tag55bAcct = block4Tag55bAcct;
    return this;
  }

   /**
   * Get block4Tag55bAcct
   * @return block4Tag55bAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag55bAcct() {
    return block4Tag55bAcct;
  }

  public void setBlock4Tag55bAcct(String block4Tag55bAcct) {
    this.block4Tag55bAcct = block4Tag55bAcct;
  }

  public Block4Tag55 block4Tag55bDcmark(String block4Tag55bDcmark) {
    this.block4Tag55bDcmark = block4Tag55bDcmark;
    return this;
  }

   /**
   * Get block4Tag55bDcmark
   * @return block4Tag55bDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag55bDcmark() {
    return block4Tag55bDcmark;
  }

  public void setBlock4Tag55bDcmark(String block4Tag55bDcmark) {
    this.block4Tag55bDcmark = block4Tag55bDcmark;
  }

  public Block4Tag55 block4Tag55bLocation(String block4Tag55bLocation) {
    this.block4Tag55bLocation = block4Tag55bLocation;
    return this;
  }

   /**
   * Get block4Tag55bLocation
   * @return block4Tag55bLocation
  **/
  @Schema(description = "")
  public String getBlock4Tag55bLocation() {
    return block4Tag55bLocation;
  }

  public void setBlock4Tag55bLocation(String block4Tag55bLocation) {
    this.block4Tag55bLocation = block4Tag55bLocation;
  }

  public Block4Tag55 block4Tag55dAcct(String block4Tag55dAcct) {
    this.block4Tag55dAcct = block4Tag55dAcct;
    return this;
  }

   /**
   * Get block4Tag55dAcct
   * @return block4Tag55dAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag55dAcct() {
    return block4Tag55dAcct;
  }

  public void setBlock4Tag55dAcct(String block4Tag55dAcct) {
    this.block4Tag55dAcct = block4Tag55dAcct;
  }

  public Block4Tag55 block4Tag55dDcmark(String block4Tag55dDcmark) {
    this.block4Tag55dDcmark = block4Tag55dDcmark;
    return this;
  }

   /**
   * Get block4Tag55dDcmark
   * @return block4Tag55dDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag55dDcmark() {
    return block4Tag55dDcmark;
  }

  public void setBlock4Tag55dDcmark(String block4Tag55dDcmark) {
    this.block4Tag55dDcmark = block4Tag55dDcmark;
  }

  public Block4Tag55 block4Tag55dNameAddr(String block4Tag55dNameAddr) {
    this.block4Tag55dNameAddr = block4Tag55dNameAddr;
    return this;
  }

   /**
   * Get block4Tag55dNameAddr
   * @return block4Tag55dNameAddr
  **/
  @Schema(description = "")
  public String getBlock4Tag55dNameAddr() {
    return block4Tag55dNameAddr;
  }

  public void setBlock4Tag55dNameAddr(String block4Tag55dNameAddr) {
    this.block4Tag55dNameAddr = block4Tag55dNameAddr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block4Tag55 block4Tag55 = (Block4Tag55) o;
    return Objects.equals(this.block4Tag55aAcct, block4Tag55.block4Tag55aAcct) &&
        Objects.equals(this.block4Tag55aBic, block4Tag55.block4Tag55aBic) &&
        Objects.equals(this.block4Tag55aDcmark, block4Tag55.block4Tag55aDcmark) &&
        Objects.equals(this.block4Tag55bAcct, block4Tag55.block4Tag55bAcct) &&
        Objects.equals(this.block4Tag55bDcmark, block4Tag55.block4Tag55bDcmark) &&
        Objects.equals(this.block4Tag55bLocation, block4Tag55.block4Tag55bLocation) &&
        Objects.equals(this.block4Tag55dAcct, block4Tag55.block4Tag55dAcct) &&
        Objects.equals(this.block4Tag55dDcmark, block4Tag55.block4Tag55dDcmark) &&
        Objects.equals(this.block4Tag55dNameAddr, block4Tag55.block4Tag55dNameAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag55aAcct, block4Tag55aBic, block4Tag55aDcmark, block4Tag55bAcct, block4Tag55bDcmark, block4Tag55bLocation, block4Tag55dAcct, block4Tag55dDcmark, block4Tag55dNameAddr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block4Tag55 {\n");
    
    sb.append("    block4Tag55aAcct: ").append(toIndentedString(block4Tag55aAcct)).append("\n");
    sb.append("    block4Tag55aBic: ").append(toIndentedString(block4Tag55aBic)).append("\n");
    sb.append("    block4Tag55aDcmark: ").append(toIndentedString(block4Tag55aDcmark)).append("\n");
    sb.append("    block4Tag55bAcct: ").append(toIndentedString(block4Tag55bAcct)).append("\n");
    sb.append("    block4Tag55bDcmark: ").append(toIndentedString(block4Tag55bDcmark)).append("\n");
    sb.append("    block4Tag55bLocation: ").append(toIndentedString(block4Tag55bLocation)).append("\n");
    sb.append("    block4Tag55dAcct: ").append(toIndentedString(block4Tag55dAcct)).append("\n");
    sb.append("    block4Tag55dDcmark: ").append(toIndentedString(block4Tag55dDcmark)).append("\n");
    sb.append("    block4Tag55dNameAddr: ").append(toIndentedString(block4Tag55dNameAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
