/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * File
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class File {
  @SerializedName("absolute")
  private Boolean absolute = null;

  @SerializedName("absoluteFile")
  private File absoluteFile = null;

  @SerializedName("absolutePath")
  private String absolutePath = null;

  @SerializedName("canonicalFile")
  private File canonicalFile = null;

  @SerializedName("canonicalPath")
  private String canonicalPath = null;

  @SerializedName("directory")
  private Boolean directory = null;

  @SerializedName("executable")
  private Boolean executable = null;

  @SerializedName("file")
  private Boolean file = null;

  @SerializedName("freeSpace")
  private Long freeSpace = null;

  @SerializedName("hidden")
  private Boolean hidden = null;

  @SerializedName("lastModified")
  private Long lastModified = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("parent")
  private String parent = null;

  @SerializedName("parentFile")
  private File parentFile = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("readable")
  private Boolean readable = null;

  @SerializedName("totalSpace")
  private Long totalSpace = null;

  @SerializedName("usableSpace")
  private Long usableSpace = null;

  @SerializedName("writable")
  private Boolean writable = null;

  public File absolute(Boolean absolute) {
    this.absolute = absolute;
    return this;
  }

   /**
   * Get absolute
   * @return absolute
  **/
  @Schema(description = "")
  public Boolean isAbsolute() {
    return absolute;
  }

  public void setAbsolute(Boolean absolute) {
    this.absolute = absolute;
  }

  public File absoluteFile(File absoluteFile) {
    this.absoluteFile = absoluteFile;
    return this;
  }

   /**
   * Get absoluteFile
   * @return absoluteFile
  **/
  @Schema(description = "")
  public File getAbsoluteFile() {
    return absoluteFile;
  }

  public void setAbsoluteFile(File absoluteFile) {
    this.absoluteFile = absoluteFile;
  }

  public File absolutePath(String absolutePath) {
    this.absolutePath = absolutePath;
    return this;
  }

   /**
   * Get absolutePath
   * @return absolutePath
  **/
  @Schema(description = "")
  public String getAbsolutePath() {
    return absolutePath;
  }

  public void setAbsolutePath(String absolutePath) {
    this.absolutePath = absolutePath;
  }

  public File canonicalFile(File canonicalFile) {
    this.canonicalFile = canonicalFile;
    return this;
  }

   /**
   * Get canonicalFile
   * @return canonicalFile
  **/
  @Schema(description = "")
  public File getCanonicalFile() {
    return canonicalFile;
  }

  public void setCanonicalFile(File canonicalFile) {
    this.canonicalFile = canonicalFile;
  }

  public File canonicalPath(String canonicalPath) {
    this.canonicalPath = canonicalPath;
    return this;
  }

   /**
   * Get canonicalPath
   * @return canonicalPath
  **/
  @Schema(description = "")
  public String getCanonicalPath() {
    return canonicalPath;
  }

  public void setCanonicalPath(String canonicalPath) {
    this.canonicalPath = canonicalPath;
  }

  public File directory(Boolean directory) {
    this.directory = directory;
    return this;
  }

   /**
   * Get directory
   * @return directory
  **/
  @Schema(description = "")
  public Boolean isDirectory() {
    return directory;
  }

  public void setDirectory(Boolean directory) {
    this.directory = directory;
  }

  public File executable(Boolean executable) {
    this.executable = executable;
    return this;
  }

   /**
   * Get executable
   * @return executable
  **/
  @Schema(description = "")
  public Boolean isExecutable() {
    return executable;
  }

  public void setExecutable(Boolean executable) {
    this.executable = executable;
  }

  public File file(Boolean file) {
    this.file = file;
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  @Schema(description = "")
  public Boolean isFile() {
    return file;
  }

  public void setFile(Boolean file) {
    this.file = file;
  }

  public File freeSpace(Long freeSpace) {
    this.freeSpace = freeSpace;
    return this;
  }

   /**
   * Get freeSpace
   * @return freeSpace
  **/
  @Schema(description = "")
  public Long getFreeSpace() {
    return freeSpace;
  }

  public void setFreeSpace(Long freeSpace) {
    this.freeSpace = freeSpace;
  }

  public File hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * Get hidden
   * @return hidden
  **/
  @Schema(description = "")
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public File lastModified(Long lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @Schema(description = "")
  public Long getLastModified() {
    return lastModified;
  }

  public void setLastModified(Long lastModified) {
    this.lastModified = lastModified;
  }

  public File name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public File parent(String parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @Schema(description = "")
  public String getParent() {
    return parent;
  }

  public void setParent(String parent) {
    this.parent = parent;
  }

  public File parentFile(File parentFile) {
    this.parentFile = parentFile;
    return this;
  }

   /**
   * Get parentFile
   * @return parentFile
  **/
  @Schema(description = "")
  public File getParentFile() {
    return parentFile;
  }

  public void setParentFile(File parentFile) {
    this.parentFile = parentFile;
  }

  public File path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @Schema(description = "")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public File readable(Boolean readable) {
    this.readable = readable;
    return this;
  }

   /**
   * Get readable
   * @return readable
  **/
  @Schema(description = "")
  public Boolean isReadable() {
    return readable;
  }

  public void setReadable(Boolean readable) {
    this.readable = readable;
  }

  public File totalSpace(Long totalSpace) {
    this.totalSpace = totalSpace;
    return this;
  }

   /**
   * Get totalSpace
   * @return totalSpace
  **/
  @Schema(description = "")
  public Long getTotalSpace() {
    return totalSpace;
  }

  public void setTotalSpace(Long totalSpace) {
    this.totalSpace = totalSpace;
  }

  public File usableSpace(Long usableSpace) {
    this.usableSpace = usableSpace;
    return this;
  }

   /**
   * Get usableSpace
   * @return usableSpace
  **/
  @Schema(description = "")
  public Long getUsableSpace() {
    return usableSpace;
  }

  public void setUsableSpace(Long usableSpace) {
    this.usableSpace = usableSpace;
  }

  public File writable(Boolean writable) {
    this.writable = writable;
    return this;
  }

   /**
   * Get writable
   * @return writable
  **/
  @Schema(description = "")
  public Boolean isWritable() {
    return writable;
  }

  public void setWritable(Boolean writable) {
    this.writable = writable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    File file = (File) o;
    return Objects.equals(this.absolute, file.absolute) &&
        Objects.equals(this.absoluteFile, file.absoluteFile) &&
        Objects.equals(this.absolutePath, file.absolutePath) &&
        Objects.equals(this.canonicalFile, file.canonicalFile) &&
        Objects.equals(this.canonicalPath, file.canonicalPath) &&
        Objects.equals(this.directory, file.directory) &&
        Objects.equals(this.executable, file.executable) &&
        Objects.equals(this.file, file.file) &&
        Objects.equals(this.freeSpace, file.freeSpace) &&
        Objects.equals(this.hidden, file.hidden) &&
        Objects.equals(this.lastModified, file.lastModified) &&
        Objects.equals(this.name, file.name) &&
        Objects.equals(this.parent, file.parent) &&
        Objects.equals(this.parentFile, file.parentFile) &&
        Objects.equals(this.path, file.path) &&
        Objects.equals(this.readable, file.readable) &&
        Objects.equals(this.totalSpace, file.totalSpace) &&
        Objects.equals(this.usableSpace, file.usableSpace) &&
        Objects.equals(this.writable, file.writable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(absolute, absoluteFile, absolutePath, canonicalFile, canonicalPath, directory, executable, file, freeSpace, hidden, lastModified, name, parent, parentFile, path, readable, totalSpace, usableSpace, writable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class File {\n");
    
    sb.append("    absolute: ").append(toIndentedString(absolute)).append("\n");
    sb.append("    absoluteFile: ").append(toIndentedString(absoluteFile)).append("\n");
    sb.append("    absolutePath: ").append(toIndentedString(absolutePath)).append("\n");
    sb.append("    canonicalFile: ").append(toIndentedString(canonicalFile)).append("\n");
    sb.append("    canonicalPath: ").append(toIndentedString(canonicalPath)).append("\n");
    sb.append("    directory: ").append(toIndentedString(directory)).append("\n");
    sb.append("    executable: ").append(toIndentedString(executable)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    freeSpace: ").append(toIndentedString(freeSpace)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    parentFile: ").append(toIndentedString(parentFile)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    readable: ").append(toIndentedString(readable)).append("\n");
    sb.append("    totalSpace: ").append(toIndentedString(totalSpace)).append("\n");
    sb.append("    usableSpace: ").append(toIndentedString(usableSpace)).append("\n");
    sb.append("    writable: ").append(toIndentedString(writable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
