/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Block4Tag50;
import io.swagger.client.model.Block4Tag52;
import io.swagger.client.model.Block4Tag53;
import io.swagger.client.model.Block4Tag54;
import io.swagger.client.model.Block4Tag55;
import io.swagger.client.model.Block4Tag56;
import io.swagger.client.model.Block4Tag57;
import io.swagger.client.model.Block4Tag59;
import io.swagger.client.model.Block4Tag70to71;
import io.swagger.client.model.Block4Tag72;
import io.swagger.client.model.Block4Tag77;
import io.swagger.client.model.MT103Block4;
import io.swagger.client.model.MT103Tag23E;
import io.swagger.client.model.MT103Tag71F;
import io.swagger.client.model.MTBlock1;
import io.swagger.client.model.MTBlock2;
import io.swagger.client.model.Tag13C;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * FinMT103
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class FinMT103 {
  @SerializedName("block1")
  private MTBlock1 block1 = null;

  @SerializedName("block2")
  private MTBlock2 block2 = null;

  @SerializedName("block2MessageType")
  private String block2MessageType = null;

  @SerializedName("block3Tag108")
  private String block3Tag108 = null;

  @SerializedName("block3Tag121")
  private String block3Tag121 = null;

  @SerializedName("block4")
  private MT103Block4 block4 = null;

  @SerializedName("block5Chk")
  private String block5Chk = null;

  @SerializedName("block5Mac")
  private String block5Mac = null;

  @SerializedName("creationDate")
  private OffsetDateTime creationDate = null;

  @SerializedName("mt103Skey")
  private Long mt103Skey = null;

  @SerializedName("mt103Tag23E")
  private List<MT103Tag23E> mt103Tag23E = null;

  @SerializedName("mt103Tag71F")
  private List<MT103Tag71F> mt103Tag71F = null;

  @SerializedName("tag13C")
  private List<Tag13C> tag13C = null;

  @SerializedName("tag70To71")
  private Block4Tag70to71 tag70To71 = null;

  @SerializedName("tags50")
  private Block4Tag50 tags50 = null;

  @SerializedName("tags52")
  private Block4Tag52 tags52 = null;

  @SerializedName("tags53")
  private Block4Tag53 tags53 = null;

  @SerializedName("tags54")
  private Block4Tag54 tags54 = null;

  @SerializedName("tags55")
  private Block4Tag55 tags55 = null;

  @SerializedName("tags56")
  private Block4Tag56 tags56 = null;

  @SerializedName("tags57")
  private Block4Tag57 tags57 = null;

  @SerializedName("tags59")
  private Block4Tag59 tags59 = null;

  @SerializedName("tags72")
  private Block4Tag72 tags72 = null;

  @SerializedName("tags77")
  private Block4Tag77 tags77 = null;

  @SerializedName("trackerID")
  private Long trackerID = null;

  public FinMT103 block1(MTBlock1 block1) {
    this.block1 = block1;
    return this;
  }

   /**
   * Get block1
   * @return block1
  **/
  @Schema(description = "")
  public MTBlock1 getBlock1() {
    return block1;
  }

  public void setBlock1(MTBlock1 block1) {
    this.block1 = block1;
  }

  public FinMT103 block2(MTBlock2 block2) {
    this.block2 = block2;
    return this;
  }

   /**
   * Get block2
   * @return block2
  **/
  @Schema(description = "")
  public MTBlock2 getBlock2() {
    return block2;
  }

  public void setBlock2(MTBlock2 block2) {
    this.block2 = block2;
  }

  public FinMT103 block2MessageType(String block2MessageType) {
    this.block2MessageType = block2MessageType;
    return this;
  }

   /**
   * Get block2MessageType
   * @return block2MessageType
  **/
  @Schema(description = "")
  public String getBlock2MessageType() {
    return block2MessageType;
  }

  public void setBlock2MessageType(String block2MessageType) {
    this.block2MessageType = block2MessageType;
  }

  public FinMT103 block3Tag108(String block3Tag108) {
    this.block3Tag108 = block3Tag108;
    return this;
  }

   /**
   * Get block3Tag108
   * @return block3Tag108
  **/
  @Schema(description = "")
  public String getBlock3Tag108() {
    return block3Tag108;
  }

  public void setBlock3Tag108(String block3Tag108) {
    this.block3Tag108 = block3Tag108;
  }

  public FinMT103 block3Tag121(String block3Tag121) {
    this.block3Tag121 = block3Tag121;
    return this;
  }

   /**
   * Get block3Tag121
   * @return block3Tag121
  **/
  @Schema(description = "")
  public String getBlock3Tag121() {
    return block3Tag121;
  }

  public void setBlock3Tag121(String block3Tag121) {
    this.block3Tag121 = block3Tag121;
  }

  public FinMT103 block4(MT103Block4 block4) {
    this.block4 = block4;
    return this;
  }

   /**
   * Get block4
   * @return block4
  **/
  @Schema(description = "")
  public MT103Block4 getBlock4() {
    return block4;
  }

  public void setBlock4(MT103Block4 block4) {
    this.block4 = block4;
  }

  public FinMT103 block5Chk(String block5Chk) {
    this.block5Chk = block5Chk;
    return this;
  }

   /**
   * Get block5Chk
   * @return block5Chk
  **/
  @Schema(description = "")
  public String getBlock5Chk() {
    return block5Chk;
  }

  public void setBlock5Chk(String block5Chk) {
    this.block5Chk = block5Chk;
  }

  public FinMT103 block5Mac(String block5Mac) {
    this.block5Mac = block5Mac;
    return this;
  }

   /**
   * Get block5Mac
   * @return block5Mac
  **/
  @Schema(description = "")
  public String getBlock5Mac() {
    return block5Mac;
  }

  public void setBlock5Mac(String block5Mac) {
    this.block5Mac = block5Mac;
  }

  public FinMT103 creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public FinMT103 mt103Skey(Long mt103Skey) {
    this.mt103Skey = mt103Skey;
    return this;
  }

   /**
   * Get mt103Skey
   * @return mt103Skey
  **/
  @Schema(description = "")
  public Long getMt103Skey() {
    return mt103Skey;
  }

  public void setMt103Skey(Long mt103Skey) {
    this.mt103Skey = mt103Skey;
  }

  public FinMT103 mt103Tag23E(List<MT103Tag23E> mt103Tag23E) {
    this.mt103Tag23E = mt103Tag23E;
    return this;
  }

  public FinMT103 addMt103Tag23EItem(MT103Tag23E mt103Tag23EItem) {
    if (this.mt103Tag23E == null) {
      this.mt103Tag23E = new ArrayList<MT103Tag23E>();
    }
    this.mt103Tag23E.add(mt103Tag23EItem);
    return this;
  }

   /**
   * Get mt103Tag23E
   * @return mt103Tag23E
  **/
  @Schema(description = "")
  public List<MT103Tag23E> getMt103Tag23E() {
    return mt103Tag23E;
  }

  public void setMt103Tag23E(List<MT103Tag23E> mt103Tag23E) {
    this.mt103Tag23E = mt103Tag23E;
  }

  public FinMT103 mt103Tag71F(List<MT103Tag71F> mt103Tag71F) {
    this.mt103Tag71F = mt103Tag71F;
    return this;
  }

  public FinMT103 addMt103Tag71FItem(MT103Tag71F mt103Tag71FItem) {
    if (this.mt103Tag71F == null) {
      this.mt103Tag71F = new ArrayList<MT103Tag71F>();
    }
    this.mt103Tag71F.add(mt103Tag71FItem);
    return this;
  }

   /**
   * Get mt103Tag71F
   * @return mt103Tag71F
  **/
  @Schema(description = "")
  public List<MT103Tag71F> getMt103Tag71F() {
    return mt103Tag71F;
  }

  public void setMt103Tag71F(List<MT103Tag71F> mt103Tag71F) {
    this.mt103Tag71F = mt103Tag71F;
  }

  public FinMT103 tag13C(List<Tag13C> tag13C) {
    this.tag13C = tag13C;
    return this;
  }

  public FinMT103 addTag13CItem(Tag13C tag13CItem) {
    if (this.tag13C == null) {
      this.tag13C = new ArrayList<Tag13C>();
    }
    this.tag13C.add(tag13CItem);
    return this;
  }

   /**
   * Get tag13C
   * @return tag13C
  **/
  @Schema(description = "")
  public List<Tag13C> getTag13C() {
    return tag13C;
  }

  public void setTag13C(List<Tag13C> tag13C) {
    this.tag13C = tag13C;
  }

  public FinMT103 tag70To71(Block4Tag70to71 tag70To71) {
    this.tag70To71 = tag70To71;
    return this;
  }

   /**
   * Get tag70To71
   * @return tag70To71
  **/
  @Schema(description = "")
  public Block4Tag70to71 getTag70To71() {
    return tag70To71;
  }

  public void setTag70To71(Block4Tag70to71 tag70To71) {
    this.tag70To71 = tag70To71;
  }

  public FinMT103 tags50(Block4Tag50 tags50) {
    this.tags50 = tags50;
    return this;
  }

   /**
   * Get tags50
   * @return tags50
  **/
  @Schema(description = "")
  public Block4Tag50 getTags50() {
    return tags50;
  }

  public void setTags50(Block4Tag50 tags50) {
    this.tags50 = tags50;
  }

  public FinMT103 tags52(Block4Tag52 tags52) {
    this.tags52 = tags52;
    return this;
  }

   /**
   * Get tags52
   * @return tags52
  **/
  @Schema(description = "")
  public Block4Tag52 getTags52() {
    return tags52;
  }

  public void setTags52(Block4Tag52 tags52) {
    this.tags52 = tags52;
  }

  public FinMT103 tags53(Block4Tag53 tags53) {
    this.tags53 = tags53;
    return this;
  }

   /**
   * Get tags53
   * @return tags53
  **/
  @Schema(description = "")
  public Block4Tag53 getTags53() {
    return tags53;
  }

  public void setTags53(Block4Tag53 tags53) {
    this.tags53 = tags53;
  }

  public FinMT103 tags54(Block4Tag54 tags54) {
    this.tags54 = tags54;
    return this;
  }

   /**
   * Get tags54
   * @return tags54
  **/
  @Schema(description = "")
  public Block4Tag54 getTags54() {
    return tags54;
  }

  public void setTags54(Block4Tag54 tags54) {
    this.tags54 = tags54;
  }

  public FinMT103 tags55(Block4Tag55 tags55) {
    this.tags55 = tags55;
    return this;
  }

   /**
   * Get tags55
   * @return tags55
  **/
  @Schema(description = "")
  public Block4Tag55 getTags55() {
    return tags55;
  }

  public void setTags55(Block4Tag55 tags55) {
    this.tags55 = tags55;
  }

  public FinMT103 tags56(Block4Tag56 tags56) {
    this.tags56 = tags56;
    return this;
  }

   /**
   * Get tags56
   * @return tags56
  **/
  @Schema(description = "")
  public Block4Tag56 getTags56() {
    return tags56;
  }

  public void setTags56(Block4Tag56 tags56) {
    this.tags56 = tags56;
  }

  public FinMT103 tags57(Block4Tag57 tags57) {
    this.tags57 = tags57;
    return this;
  }

   /**
   * Get tags57
   * @return tags57
  **/
  @Schema(description = "")
  public Block4Tag57 getTags57() {
    return tags57;
  }

  public void setTags57(Block4Tag57 tags57) {
    this.tags57 = tags57;
  }

  public FinMT103 tags59(Block4Tag59 tags59) {
    this.tags59 = tags59;
    return this;
  }

   /**
   * Get tags59
   * @return tags59
  **/
  @Schema(description = "")
  public Block4Tag59 getTags59() {
    return tags59;
  }

  public void setTags59(Block4Tag59 tags59) {
    this.tags59 = tags59;
  }

  public FinMT103 tags72(Block4Tag72 tags72) {
    this.tags72 = tags72;
    return this;
  }

   /**
   * Get tags72
   * @return tags72
  **/
  @Schema(description = "")
  public Block4Tag72 getTags72() {
    return tags72;
  }

  public void setTags72(Block4Tag72 tags72) {
    this.tags72 = tags72;
  }

  public FinMT103 tags77(Block4Tag77 tags77) {
    this.tags77 = tags77;
    return this;
  }

   /**
   * Get tags77
   * @return tags77
  **/
  @Schema(description = "")
  public Block4Tag77 getTags77() {
    return tags77;
  }

  public void setTags77(Block4Tag77 tags77) {
    this.tags77 = tags77;
  }

  public FinMT103 trackerID(Long trackerID) {
    this.trackerID = trackerID;
    return this;
  }

   /**
   * Get trackerID
   * @return trackerID
  **/
  @Schema(description = "")
  public Long getTrackerID() {
    return trackerID;
  }

  public void setTrackerID(Long trackerID) {
    this.trackerID = trackerID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinMT103 finMT103 = (FinMT103) o;
    return Objects.equals(this.block1, finMT103.block1) &&
        Objects.equals(this.block2, finMT103.block2) &&
        Objects.equals(this.block2MessageType, finMT103.block2MessageType) &&
        Objects.equals(this.block3Tag108, finMT103.block3Tag108) &&
        Objects.equals(this.block3Tag121, finMT103.block3Tag121) &&
        Objects.equals(this.block4, finMT103.block4) &&
        Objects.equals(this.block5Chk, finMT103.block5Chk) &&
        Objects.equals(this.block5Mac, finMT103.block5Mac) &&
        Objects.equals(this.creationDate, finMT103.creationDate) &&
        Objects.equals(this.mt103Skey, finMT103.mt103Skey) &&
        Objects.equals(this.mt103Tag23E, finMT103.mt103Tag23E) &&
        Objects.equals(this.mt103Tag71F, finMT103.mt103Tag71F) &&
        Objects.equals(this.tag13C, finMT103.tag13C) &&
        Objects.equals(this.tag70To71, finMT103.tag70To71) &&
        Objects.equals(this.tags50, finMT103.tags50) &&
        Objects.equals(this.tags52, finMT103.tags52) &&
        Objects.equals(this.tags53, finMT103.tags53) &&
        Objects.equals(this.tags54, finMT103.tags54) &&
        Objects.equals(this.tags55, finMT103.tags55) &&
        Objects.equals(this.tags56, finMT103.tags56) &&
        Objects.equals(this.tags57, finMT103.tags57) &&
        Objects.equals(this.tags59, finMT103.tags59) &&
        Objects.equals(this.tags72, finMT103.tags72) &&
        Objects.equals(this.tags77, finMT103.tags77) &&
        Objects.equals(this.trackerID, finMT103.trackerID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block1, block2, block2MessageType, block3Tag108, block3Tag121, block4, block5Chk, block5Mac, creationDate, mt103Skey, mt103Tag23E, mt103Tag71F, tag13C, tag70To71, tags50, tags52, tags53, tags54, tags55, tags56, tags57, tags59, tags72, tags77, trackerID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinMT103 {\n");
    
    sb.append("    block1: ").append(toIndentedString(block1)).append("\n");
    sb.append("    block2: ").append(toIndentedString(block2)).append("\n");
    sb.append("    block2MessageType: ").append(toIndentedString(block2MessageType)).append("\n");
    sb.append("    block3Tag108: ").append(toIndentedString(block3Tag108)).append("\n");
    sb.append("    block3Tag121: ").append(toIndentedString(block3Tag121)).append("\n");
    sb.append("    block4: ").append(toIndentedString(block4)).append("\n");
    sb.append("    block5Chk: ").append(toIndentedString(block5Chk)).append("\n");
    sb.append("    block5Mac: ").append(toIndentedString(block5Mac)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    mt103Skey: ").append(toIndentedString(mt103Skey)).append("\n");
    sb.append("    mt103Tag23E: ").append(toIndentedString(mt103Tag23E)).append("\n");
    sb.append("    mt103Tag71F: ").append(toIndentedString(mt103Tag71F)).append("\n");
    sb.append("    tag13C: ").append(toIndentedString(tag13C)).append("\n");
    sb.append("    tag70To71: ").append(toIndentedString(tag70To71)).append("\n");
    sb.append("    tags50: ").append(toIndentedString(tags50)).append("\n");
    sb.append("    tags52: ").append(toIndentedString(tags52)).append("\n");
    sb.append("    tags53: ").append(toIndentedString(tags53)).append("\n");
    sb.append("    tags54: ").append(toIndentedString(tags54)).append("\n");
    sb.append("    tags55: ").append(toIndentedString(tags55)).append("\n");
    sb.append("    tags56: ").append(toIndentedString(tags56)).append("\n");
    sb.append("    tags57: ").append(toIndentedString(tags57)).append("\n");
    sb.append("    tags59: ").append(toIndentedString(tags59)).append("\n");
    sb.append("    tags72: ").append(toIndentedString(tags72)).append("\n");
    sb.append("    tags77: ").append(toIndentedString(tags77)).append("\n");
    sb.append("    trackerID: ").append(toIndentedString(trackerID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
