/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * MT103Tag71F
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class MT103Tag71F {
  @SerializedName("mt103Skey")
  private Long mt103Skey = null;

  @SerializedName("mt103Tag71FCurrency")
  private String mt103Tag71FCurrency = null;

  @SerializedName("mt103Tag71FIndex")
  private Long mt103Tag71FIndex = null;

  @SerializedName("mt103Tag71FSenderCharge")
  private BigDecimal mt103Tag71FSenderCharge = null;

  @SerializedName("mt103Tag71FSkey")
  private Long mt103Tag71FSkey = null;

  public MT103Tag71F mt103Skey(Long mt103Skey) {
    this.mt103Skey = mt103Skey;
    return this;
  }

   /**
   * Get mt103Skey
   * @return mt103Skey
  **/
  @Schema(description = "")
  public Long getMt103Skey() {
    return mt103Skey;
  }

  public void setMt103Skey(Long mt103Skey) {
    this.mt103Skey = mt103Skey;
  }

  public MT103Tag71F mt103Tag71FCurrency(String mt103Tag71FCurrency) {
    this.mt103Tag71FCurrency = mt103Tag71FCurrency;
    return this;
  }

   /**
   * Get mt103Tag71FCurrency
   * @return mt103Tag71FCurrency
  **/
  @Schema(description = "")
  public String getMt103Tag71FCurrency() {
    return mt103Tag71FCurrency;
  }

  public void setMt103Tag71FCurrency(String mt103Tag71FCurrency) {
    this.mt103Tag71FCurrency = mt103Tag71FCurrency;
  }

  public MT103Tag71F mt103Tag71FIndex(Long mt103Tag71FIndex) {
    this.mt103Tag71FIndex = mt103Tag71FIndex;
    return this;
  }

   /**
   * Get mt103Tag71FIndex
   * @return mt103Tag71FIndex
  **/
  @Schema(description = "")
  public Long getMt103Tag71FIndex() {
    return mt103Tag71FIndex;
  }

  public void setMt103Tag71FIndex(Long mt103Tag71FIndex) {
    this.mt103Tag71FIndex = mt103Tag71FIndex;
  }

  public MT103Tag71F mt103Tag71FSenderCharge(BigDecimal mt103Tag71FSenderCharge) {
    this.mt103Tag71FSenderCharge = mt103Tag71FSenderCharge;
    return this;
  }

   /**
   * Get mt103Tag71FSenderCharge
   * @return mt103Tag71FSenderCharge
  **/
  @Schema(description = "")
  public BigDecimal getMt103Tag71FSenderCharge() {
    return mt103Tag71FSenderCharge;
  }

  public void setMt103Tag71FSenderCharge(BigDecimal mt103Tag71FSenderCharge) {
    this.mt103Tag71FSenderCharge = mt103Tag71FSenderCharge;
  }

  public MT103Tag71F mt103Tag71FSkey(Long mt103Tag71FSkey) {
    this.mt103Tag71FSkey = mt103Tag71FSkey;
    return this;
  }

   /**
   * Get mt103Tag71FSkey
   * @return mt103Tag71FSkey
  **/
  @Schema(description = "")
  public Long getMt103Tag71FSkey() {
    return mt103Tag71FSkey;
  }

  public void setMt103Tag71FSkey(Long mt103Tag71FSkey) {
    this.mt103Tag71FSkey = mt103Tag71FSkey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MT103Tag71F mt103Tag71F = (MT103Tag71F) o;
    return Objects.equals(this.mt103Skey, mt103Tag71F.mt103Skey) &&
        Objects.equals(this.mt103Tag71FCurrency, mt103Tag71F.mt103Tag71FCurrency) &&
        Objects.equals(this.mt103Tag71FIndex, mt103Tag71F.mt103Tag71FIndex) &&
        Objects.equals(this.mt103Tag71FSenderCharge, mt103Tag71F.mt103Tag71FSenderCharge) &&
        Objects.equals(this.mt103Tag71FSkey, mt103Tag71F.mt103Tag71FSkey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mt103Skey, mt103Tag71FCurrency, mt103Tag71FIndex, mt103Tag71FSenderCharge, mt103Tag71FSkey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MT103Tag71F {\n");
    
    sb.append("    mt103Skey: ").append(toIndentedString(mt103Skey)).append("\n");
    sb.append("    mt103Tag71FCurrency: ").append(toIndentedString(mt103Tag71FCurrency)).append("\n");
    sb.append("    mt103Tag71FIndex: ").append(toIndentedString(mt103Tag71FIndex)).append("\n");
    sb.append("    mt103Tag71FSenderCharge: ").append(toIndentedString(mt103Tag71FSenderCharge)).append("\n");
    sb.append("    mt103Tag71FSkey: ").append(toIndentedString(mt103Tag71FSkey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
