/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MT103Tag23E
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class MT103Tag23E {
  @SerializedName("mt103Skey")
  private Long mt103Skey = null;

  @SerializedName("mt103Tag23EAddnInfo")
  private String mt103Tag23EAddnInfo = null;

  @SerializedName("mt103Tag23ECode")
  private String mt103Tag23ECode = null;

  @SerializedName("mt103Tag23EIndex")
  private Long mt103Tag23EIndex = null;

  @SerializedName("mt103Tag23ESkey")
  private Long mt103Tag23ESkey = null;

  public MT103Tag23E mt103Skey(Long mt103Skey) {
    this.mt103Skey = mt103Skey;
    return this;
  }

   /**
   * Get mt103Skey
   * @return mt103Skey
  **/
  @Schema(description = "")
  public Long getMt103Skey() {
    return mt103Skey;
  }

  public void setMt103Skey(Long mt103Skey) {
    this.mt103Skey = mt103Skey;
  }

  public MT103Tag23E mt103Tag23EAddnInfo(String mt103Tag23EAddnInfo) {
    this.mt103Tag23EAddnInfo = mt103Tag23EAddnInfo;
    return this;
  }

   /**
   * Get mt103Tag23EAddnInfo
   * @return mt103Tag23EAddnInfo
  **/
  @Schema(description = "")
  public String getMt103Tag23EAddnInfo() {
    return mt103Tag23EAddnInfo;
  }

  public void setMt103Tag23EAddnInfo(String mt103Tag23EAddnInfo) {
    this.mt103Tag23EAddnInfo = mt103Tag23EAddnInfo;
  }

  public MT103Tag23E mt103Tag23ECode(String mt103Tag23ECode) {
    this.mt103Tag23ECode = mt103Tag23ECode;
    return this;
  }

   /**
   * Get mt103Tag23ECode
   * @return mt103Tag23ECode
  **/
  @Schema(description = "")
  public String getMt103Tag23ECode() {
    return mt103Tag23ECode;
  }

  public void setMt103Tag23ECode(String mt103Tag23ECode) {
    this.mt103Tag23ECode = mt103Tag23ECode;
  }

  public MT103Tag23E mt103Tag23EIndex(Long mt103Tag23EIndex) {
    this.mt103Tag23EIndex = mt103Tag23EIndex;
    return this;
  }

   /**
   * Get mt103Tag23EIndex
   * @return mt103Tag23EIndex
  **/
  @Schema(description = "")
  public Long getMt103Tag23EIndex() {
    return mt103Tag23EIndex;
  }

  public void setMt103Tag23EIndex(Long mt103Tag23EIndex) {
    this.mt103Tag23EIndex = mt103Tag23EIndex;
  }

  public MT103Tag23E mt103Tag23ESkey(Long mt103Tag23ESkey) {
    this.mt103Tag23ESkey = mt103Tag23ESkey;
    return this;
  }

   /**
   * Get mt103Tag23ESkey
   * @return mt103Tag23ESkey
  **/
  @Schema(description = "")
  public Long getMt103Tag23ESkey() {
    return mt103Tag23ESkey;
  }

  public void setMt103Tag23ESkey(Long mt103Tag23ESkey) {
    this.mt103Tag23ESkey = mt103Tag23ESkey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MT103Tag23E mt103Tag23E = (MT103Tag23E) o;
    return Objects.equals(this.mt103Skey, mt103Tag23E.mt103Skey) &&
        Objects.equals(this.mt103Tag23EAddnInfo, mt103Tag23E.mt103Tag23EAddnInfo) &&
        Objects.equals(this.mt103Tag23ECode, mt103Tag23E.mt103Tag23ECode) &&
        Objects.equals(this.mt103Tag23EIndex, mt103Tag23E.mt103Tag23EIndex) &&
        Objects.equals(this.mt103Tag23ESkey, mt103Tag23E.mt103Tag23ESkey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mt103Skey, mt103Tag23EAddnInfo, mt103Tag23ECode, mt103Tag23EIndex, mt103Tag23ESkey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MT103Tag23E {\n");
    
    sb.append("    mt103Skey: ").append(toIndentedString(mt103Skey)).append("\n");
    sb.append("    mt103Tag23EAddnInfo: ").append(toIndentedString(mt103Tag23EAddnInfo)).append("\n");
    sb.append("    mt103Tag23ECode: ").append(toIndentedString(mt103Tag23ECode)).append("\n");
    sb.append("    mt103Tag23EIndex: ").append(toIndentedString(mt103Tag23EIndex)).append("\n");
    sb.append("    mt103Tag23ESkey: ").append(toIndentedString(mt103Tag23ESkey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
