/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * MT103Block4
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class MT103Block4 {
  @SerializedName("block4Tag20")
  private String block4Tag20 = null;

  @SerializedName("block4Tag23b")
  private String block4Tag23b = null;

  @SerializedName("block4Tag26t")
  private String block4Tag26t = null;

  @SerializedName("block4Tag32aCurrency")
  private String block4Tag32aCurrency = null;

  @SerializedName("block4Tag32aDate")
  private String block4Tag32aDate = null;

  @SerializedName("block4Tag32aSettledAmnt")
  private BigDecimal block4Tag32aSettledAmnt = null;

  @SerializedName("block4Tag33bCurrency")
  private String block4Tag33bCurrency = null;

  @SerializedName("block4Tag33bInstrucAmnt")
  private BigDecimal block4Tag33bInstrucAmnt = null;

  @SerializedName("block4Tag36")
  private String block4Tag36 = null;

  @SerializedName("block4Tag51aAcct")
  private String block4Tag51aAcct = null;

  @SerializedName("block4Tag51aBic")
  private String block4Tag51aBic = null;

  @SerializedName("block4Tag51aDcmark")
  private String block4Tag51aDcmark = null;

  @SerializedName("block4Tag56c")
  private String block4Tag56c = null;

  @SerializedName("block4Tag57c")
  private String block4Tag57c = null;

  public MT103Block4 block4Tag20(String block4Tag20) {
    this.block4Tag20 = block4Tag20;
    return this;
  }

   /**
   * Get block4Tag20
   * @return block4Tag20
  **/
  @Schema(description = "")
  public String getBlock4Tag20() {
    return block4Tag20;
  }

  public void setBlock4Tag20(String block4Tag20) {
    this.block4Tag20 = block4Tag20;
  }

  public MT103Block4 block4Tag23b(String block4Tag23b) {
    this.block4Tag23b = block4Tag23b;
    return this;
  }

   /**
   * Get block4Tag23b
   * @return block4Tag23b
  **/
  @Schema(description = "")
  public String getBlock4Tag23b() {
    return block4Tag23b;
  }

  public void setBlock4Tag23b(String block4Tag23b) {
    this.block4Tag23b = block4Tag23b;
  }

  public MT103Block4 block4Tag26t(String block4Tag26t) {
    this.block4Tag26t = block4Tag26t;
    return this;
  }

   /**
   * Get block4Tag26t
   * @return block4Tag26t
  **/
  @Schema(description = "")
  public String getBlock4Tag26t() {
    return block4Tag26t;
  }

  public void setBlock4Tag26t(String block4Tag26t) {
    this.block4Tag26t = block4Tag26t;
  }

  public MT103Block4 block4Tag32aCurrency(String block4Tag32aCurrency) {
    this.block4Tag32aCurrency = block4Tag32aCurrency;
    return this;
  }

   /**
   * Get block4Tag32aCurrency
   * @return block4Tag32aCurrency
  **/
  @Schema(description = "")
  public String getBlock4Tag32aCurrency() {
    return block4Tag32aCurrency;
  }

  public void setBlock4Tag32aCurrency(String block4Tag32aCurrency) {
    this.block4Tag32aCurrency = block4Tag32aCurrency;
  }

  public MT103Block4 block4Tag32aDate(String block4Tag32aDate) {
    this.block4Tag32aDate = block4Tag32aDate;
    return this;
  }

   /**
   * Get block4Tag32aDate
   * @return block4Tag32aDate
  **/
  @Schema(description = "")
  public String getBlock4Tag32aDate() {
    return block4Tag32aDate;
  }

  public void setBlock4Tag32aDate(String block4Tag32aDate) {
    this.block4Tag32aDate = block4Tag32aDate;
  }

  public MT103Block4 block4Tag32aSettledAmnt(BigDecimal block4Tag32aSettledAmnt) {
    this.block4Tag32aSettledAmnt = block4Tag32aSettledAmnt;
    return this;
  }

   /**
   * Get block4Tag32aSettledAmnt
   * @return block4Tag32aSettledAmnt
  **/
  @Schema(description = "")
  public BigDecimal getBlock4Tag32aSettledAmnt() {
    return block4Tag32aSettledAmnt;
  }

  public void setBlock4Tag32aSettledAmnt(BigDecimal block4Tag32aSettledAmnt) {
    this.block4Tag32aSettledAmnt = block4Tag32aSettledAmnt;
  }

  public MT103Block4 block4Tag33bCurrency(String block4Tag33bCurrency) {
    this.block4Tag33bCurrency = block4Tag33bCurrency;
    return this;
  }

   /**
   * Get block4Tag33bCurrency
   * @return block4Tag33bCurrency
  **/
  @Schema(description = "")
  public String getBlock4Tag33bCurrency() {
    return block4Tag33bCurrency;
  }

  public void setBlock4Tag33bCurrency(String block4Tag33bCurrency) {
    this.block4Tag33bCurrency = block4Tag33bCurrency;
  }

  public MT103Block4 block4Tag33bInstrucAmnt(BigDecimal block4Tag33bInstrucAmnt) {
    this.block4Tag33bInstrucAmnt = block4Tag33bInstrucAmnt;
    return this;
  }

   /**
   * Get block4Tag33bInstrucAmnt
   * @return block4Tag33bInstrucAmnt
  **/
  @Schema(description = "")
  public BigDecimal getBlock4Tag33bInstrucAmnt() {
    return block4Tag33bInstrucAmnt;
  }

  public void setBlock4Tag33bInstrucAmnt(BigDecimal block4Tag33bInstrucAmnt) {
    this.block4Tag33bInstrucAmnt = block4Tag33bInstrucAmnt;
  }

  public MT103Block4 block4Tag36(String block4Tag36) {
    this.block4Tag36 = block4Tag36;
    return this;
  }

   /**
   * Get block4Tag36
   * @return block4Tag36
  **/
  @Schema(description = "")
  public String getBlock4Tag36() {
    return block4Tag36;
  }

  public void setBlock4Tag36(String block4Tag36) {
    this.block4Tag36 = block4Tag36;
  }

  public MT103Block4 block4Tag51aAcct(String block4Tag51aAcct) {
    this.block4Tag51aAcct = block4Tag51aAcct;
    return this;
  }

   /**
   * Get block4Tag51aAcct
   * @return block4Tag51aAcct
  **/
  @Schema(description = "")
  public String getBlock4Tag51aAcct() {
    return block4Tag51aAcct;
  }

  public void setBlock4Tag51aAcct(String block4Tag51aAcct) {
    this.block4Tag51aAcct = block4Tag51aAcct;
  }

  public MT103Block4 block4Tag51aBic(String block4Tag51aBic) {
    this.block4Tag51aBic = block4Tag51aBic;
    return this;
  }

   /**
   * Get block4Tag51aBic
   * @return block4Tag51aBic
  **/
  @Schema(description = "")
  public String getBlock4Tag51aBic() {
    return block4Tag51aBic;
  }

  public void setBlock4Tag51aBic(String block4Tag51aBic) {
    this.block4Tag51aBic = block4Tag51aBic;
  }

  public MT103Block4 block4Tag51aDcmark(String block4Tag51aDcmark) {
    this.block4Tag51aDcmark = block4Tag51aDcmark;
    return this;
  }

   /**
   * Get block4Tag51aDcmark
   * @return block4Tag51aDcmark
  **/
  @Schema(description = "")
  public String getBlock4Tag51aDcmark() {
    return block4Tag51aDcmark;
  }

  public void setBlock4Tag51aDcmark(String block4Tag51aDcmark) {
    this.block4Tag51aDcmark = block4Tag51aDcmark;
  }

  public MT103Block4 block4Tag56c(String block4Tag56c) {
    this.block4Tag56c = block4Tag56c;
    return this;
  }

   /**
   * Get block4Tag56c
   * @return block4Tag56c
  **/
  @Schema(description = "")
  public String getBlock4Tag56c() {
    return block4Tag56c;
  }

  public void setBlock4Tag56c(String block4Tag56c) {
    this.block4Tag56c = block4Tag56c;
  }

  public MT103Block4 block4Tag57c(String block4Tag57c) {
    this.block4Tag57c = block4Tag57c;
    return this;
  }

   /**
   * Get block4Tag57c
   * @return block4Tag57c
  **/
  @Schema(description = "")
  public String getBlock4Tag57c() {
    return block4Tag57c;
  }

  public void setBlock4Tag57c(String block4Tag57c) {
    this.block4Tag57c = block4Tag57c;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MT103Block4 mt103Block4 = (MT103Block4) o;
    return Objects.equals(this.block4Tag20, mt103Block4.block4Tag20) &&
        Objects.equals(this.block4Tag23b, mt103Block4.block4Tag23b) &&
        Objects.equals(this.block4Tag26t, mt103Block4.block4Tag26t) &&
        Objects.equals(this.block4Tag32aCurrency, mt103Block4.block4Tag32aCurrency) &&
        Objects.equals(this.block4Tag32aDate, mt103Block4.block4Tag32aDate) &&
        Objects.equals(this.block4Tag32aSettledAmnt, mt103Block4.block4Tag32aSettledAmnt) &&
        Objects.equals(this.block4Tag33bCurrency, mt103Block4.block4Tag33bCurrency) &&
        Objects.equals(this.block4Tag33bInstrucAmnt, mt103Block4.block4Tag33bInstrucAmnt) &&
        Objects.equals(this.block4Tag36, mt103Block4.block4Tag36) &&
        Objects.equals(this.block4Tag51aAcct, mt103Block4.block4Tag51aAcct) &&
        Objects.equals(this.block4Tag51aBic, mt103Block4.block4Tag51aBic) &&
        Objects.equals(this.block4Tag51aDcmark, mt103Block4.block4Tag51aDcmark) &&
        Objects.equals(this.block4Tag56c, mt103Block4.block4Tag56c) &&
        Objects.equals(this.block4Tag57c, mt103Block4.block4Tag57c);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block4Tag20, block4Tag23b, block4Tag26t, block4Tag32aCurrency, block4Tag32aDate, block4Tag32aSettledAmnt, block4Tag33bCurrency, block4Tag33bInstrucAmnt, block4Tag36, block4Tag51aAcct, block4Tag51aBic, block4Tag51aDcmark, block4Tag56c, block4Tag57c);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MT103Block4 {\n");
    
    sb.append("    block4Tag20: ").append(toIndentedString(block4Tag20)).append("\n");
    sb.append("    block4Tag23b: ").append(toIndentedString(block4Tag23b)).append("\n");
    sb.append("    block4Tag26t: ").append(toIndentedString(block4Tag26t)).append("\n");
    sb.append("    block4Tag32aCurrency: ").append(toIndentedString(block4Tag32aCurrency)).append("\n");
    sb.append("    block4Tag32aDate: ").append(toIndentedString(block4Tag32aDate)).append("\n");
    sb.append("    block4Tag32aSettledAmnt: ").append(toIndentedString(block4Tag32aSettledAmnt)).append("\n");
    sb.append("    block4Tag33bCurrency: ").append(toIndentedString(block4Tag33bCurrency)).append("\n");
    sb.append("    block4Tag33bInstrucAmnt: ").append(toIndentedString(block4Tag33bInstrucAmnt)).append("\n");
    sb.append("    block4Tag36: ").append(toIndentedString(block4Tag36)).append("\n");
    sb.append("    block4Tag51aAcct: ").append(toIndentedString(block4Tag51aAcct)).append("\n");
    sb.append("    block4Tag51aBic: ").append(toIndentedString(block4Tag51aBic)).append("\n");
    sb.append("    block4Tag51aDcmark: ").append(toIndentedString(block4Tag51aDcmark)).append("\n");
    sb.append("    block4Tag56c: ").append(toIndentedString(block4Tag56c)).append("\n");
    sb.append("    block4Tag57c: ").append(toIndentedString(block4Tag57c)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
