/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * MTBlock2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class MTBlock2 {
  @SerializedName("block2DeliveryMonitor")
  private String block2DeliveryMonitor = null;

  @SerializedName("block2InOutInd")
  private String block2InOutInd = null;

  @SerializedName("block2MIRDate")
  private String block2MIRDate = null;

  @SerializedName("block2MIRLogicalTerminal")
  private String block2MIRLogicalTerminal = null;

  @SerializedName("block2MIRSeqNum")
  private String block2MIRSeqNum = null;

  @SerializedName("block2MIRSessNum")
  private String block2MIRSessNum = null;

  @SerializedName("block2MessagePriority")
  private String block2MessagePriority = null;

  @SerializedName("block2OBSPeriod")
  private String block2OBSPeriod = null;

  @SerializedName("block2ReceiverAddr")
  private String block2ReceiverAddr = null;

  @SerializedName("block2ReceiverOutDate")
  private String block2ReceiverOutDate = null;

  @SerializedName("block2ReceiverOutTime")
  private String block2ReceiverOutTime = null;

  @SerializedName("block2SenderInTime")
  private String block2SenderInTime = null;

  @SerializedName("receiverTimeStamp")
  private OffsetDateTime receiverTimeStamp = null;

  @SerializedName("senderTimeStamp")
  private OffsetDateTime senderTimeStamp = null;

  public MTBlock2 block2DeliveryMonitor(String block2DeliveryMonitor) {
    this.block2DeliveryMonitor = block2DeliveryMonitor;
    return this;
  }

   /**
   * Get block2DeliveryMonitor
   * @return block2DeliveryMonitor
  **/
  @Schema(description = "")
  public String getBlock2DeliveryMonitor() {
    return block2DeliveryMonitor;
  }

  public void setBlock2DeliveryMonitor(String block2DeliveryMonitor) {
    this.block2DeliveryMonitor = block2DeliveryMonitor;
  }

  public MTBlock2 block2InOutInd(String block2InOutInd) {
    this.block2InOutInd = block2InOutInd;
    return this;
  }

   /**
   * Get block2InOutInd
   * @return block2InOutInd
  **/
  @Schema(description = "")
  public String getBlock2InOutInd() {
    return block2InOutInd;
  }

  public void setBlock2InOutInd(String block2InOutInd) {
    this.block2InOutInd = block2InOutInd;
  }

  public MTBlock2 block2MIRDate(String block2MIRDate) {
    this.block2MIRDate = block2MIRDate;
    return this;
  }

   /**
   * Get block2MIRDate
   * @return block2MIRDate
  **/
  @Schema(description = "")
  public String getBlock2MIRDate() {
    return block2MIRDate;
  }

  public void setBlock2MIRDate(String block2MIRDate) {
    this.block2MIRDate = block2MIRDate;
  }

  public MTBlock2 block2MIRLogicalTerminal(String block2MIRLogicalTerminal) {
    this.block2MIRLogicalTerminal = block2MIRLogicalTerminal;
    return this;
  }

   /**
   * Get block2MIRLogicalTerminal
   * @return block2MIRLogicalTerminal
  **/
  @Schema(description = "")
  public String getBlock2MIRLogicalTerminal() {
    return block2MIRLogicalTerminal;
  }

  public void setBlock2MIRLogicalTerminal(String block2MIRLogicalTerminal) {
    this.block2MIRLogicalTerminal = block2MIRLogicalTerminal;
  }

  public MTBlock2 block2MIRSeqNum(String block2MIRSeqNum) {
    this.block2MIRSeqNum = block2MIRSeqNum;
    return this;
  }

   /**
   * Get block2MIRSeqNum
   * @return block2MIRSeqNum
  **/
  @Schema(description = "")
  public String getBlock2MIRSeqNum() {
    return block2MIRSeqNum;
  }

  public void setBlock2MIRSeqNum(String block2MIRSeqNum) {
    this.block2MIRSeqNum = block2MIRSeqNum;
  }

  public MTBlock2 block2MIRSessNum(String block2MIRSessNum) {
    this.block2MIRSessNum = block2MIRSessNum;
    return this;
  }

   /**
   * Get block2MIRSessNum
   * @return block2MIRSessNum
  **/
  @Schema(description = "")
  public String getBlock2MIRSessNum() {
    return block2MIRSessNum;
  }

  public void setBlock2MIRSessNum(String block2MIRSessNum) {
    this.block2MIRSessNum = block2MIRSessNum;
  }

  public MTBlock2 block2MessagePriority(String block2MessagePriority) {
    this.block2MessagePriority = block2MessagePriority;
    return this;
  }

   /**
   * Get block2MessagePriority
   * @return block2MessagePriority
  **/
  @Schema(description = "")
  public String getBlock2MessagePriority() {
    return block2MessagePriority;
  }

  public void setBlock2MessagePriority(String block2MessagePriority) {
    this.block2MessagePriority = block2MessagePriority;
  }

  public MTBlock2 block2OBSPeriod(String block2OBSPeriod) {
    this.block2OBSPeriod = block2OBSPeriod;
    return this;
  }

   /**
   * Get block2OBSPeriod
   * @return block2OBSPeriod
  **/
  @Schema(description = "")
  public String getBlock2OBSPeriod() {
    return block2OBSPeriod;
  }

  public void setBlock2OBSPeriod(String block2OBSPeriod) {
    this.block2OBSPeriod = block2OBSPeriod;
  }

  public MTBlock2 block2ReceiverAddr(String block2ReceiverAddr) {
    this.block2ReceiverAddr = block2ReceiverAddr;
    return this;
  }

   /**
   * Get block2ReceiverAddr
   * @return block2ReceiverAddr
  **/
  @Schema(description = "")
  public String getBlock2ReceiverAddr() {
    return block2ReceiverAddr;
  }

  public void setBlock2ReceiverAddr(String block2ReceiverAddr) {
    this.block2ReceiverAddr = block2ReceiverAddr;
  }

  public MTBlock2 block2ReceiverOutDate(String block2ReceiverOutDate) {
    this.block2ReceiverOutDate = block2ReceiverOutDate;
    return this;
  }

   /**
   * Get block2ReceiverOutDate
   * @return block2ReceiverOutDate
  **/
  @Schema(description = "")
  public String getBlock2ReceiverOutDate() {
    return block2ReceiverOutDate;
  }

  public void setBlock2ReceiverOutDate(String block2ReceiverOutDate) {
    this.block2ReceiverOutDate = block2ReceiverOutDate;
  }

  public MTBlock2 block2ReceiverOutTime(String block2ReceiverOutTime) {
    this.block2ReceiverOutTime = block2ReceiverOutTime;
    return this;
  }

   /**
   * Get block2ReceiverOutTime
   * @return block2ReceiverOutTime
  **/
  @Schema(description = "")
  public String getBlock2ReceiverOutTime() {
    return block2ReceiverOutTime;
  }

  public void setBlock2ReceiverOutTime(String block2ReceiverOutTime) {
    this.block2ReceiverOutTime = block2ReceiverOutTime;
  }

  public MTBlock2 block2SenderInTime(String block2SenderInTime) {
    this.block2SenderInTime = block2SenderInTime;
    return this;
  }

   /**
   * Get block2SenderInTime
   * @return block2SenderInTime
  **/
  @Schema(description = "")
  public String getBlock2SenderInTime() {
    return block2SenderInTime;
  }

  public void setBlock2SenderInTime(String block2SenderInTime) {
    this.block2SenderInTime = block2SenderInTime;
  }

  public MTBlock2 receiverTimeStamp(OffsetDateTime receiverTimeStamp) {
    this.receiverTimeStamp = receiverTimeStamp;
    return this;
  }

   /**
   * Get receiverTimeStamp
   * @return receiverTimeStamp
  **/
  @Schema(description = "")
  public OffsetDateTime getReceiverTimeStamp() {
    return receiverTimeStamp;
  }

  public void setReceiverTimeStamp(OffsetDateTime receiverTimeStamp) {
    this.receiverTimeStamp = receiverTimeStamp;
  }

  public MTBlock2 senderTimeStamp(OffsetDateTime senderTimeStamp) {
    this.senderTimeStamp = senderTimeStamp;
    return this;
  }

   /**
   * Get senderTimeStamp
   * @return senderTimeStamp
  **/
  @Schema(description = "")
  public OffsetDateTime getSenderTimeStamp() {
    return senderTimeStamp;
  }

  public void setSenderTimeStamp(OffsetDateTime senderTimeStamp) {
    this.senderTimeStamp = senderTimeStamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MTBlock2 mtBlock2 = (MTBlock2) o;
    return Objects.equals(this.block2DeliveryMonitor, mtBlock2.block2DeliveryMonitor) &&
        Objects.equals(this.block2InOutInd, mtBlock2.block2InOutInd) &&
        Objects.equals(this.block2MIRDate, mtBlock2.block2MIRDate) &&
        Objects.equals(this.block2MIRLogicalTerminal, mtBlock2.block2MIRLogicalTerminal) &&
        Objects.equals(this.block2MIRSeqNum, mtBlock2.block2MIRSeqNum) &&
        Objects.equals(this.block2MIRSessNum, mtBlock2.block2MIRSessNum) &&
        Objects.equals(this.block2MessagePriority, mtBlock2.block2MessagePriority) &&
        Objects.equals(this.block2OBSPeriod, mtBlock2.block2OBSPeriod) &&
        Objects.equals(this.block2ReceiverAddr, mtBlock2.block2ReceiverAddr) &&
        Objects.equals(this.block2ReceiverOutDate, mtBlock2.block2ReceiverOutDate) &&
        Objects.equals(this.block2ReceiverOutTime, mtBlock2.block2ReceiverOutTime) &&
        Objects.equals(this.block2SenderInTime, mtBlock2.block2SenderInTime) &&
        Objects.equals(this.receiverTimeStamp, mtBlock2.receiverTimeStamp) &&
        Objects.equals(this.senderTimeStamp, mtBlock2.senderTimeStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block2DeliveryMonitor, block2InOutInd, block2MIRDate, block2MIRLogicalTerminal, block2MIRSeqNum, block2MIRSessNum, block2MessagePriority, block2OBSPeriod, block2ReceiverAddr, block2ReceiverOutDate, block2ReceiverOutTime, block2SenderInTime, receiverTimeStamp, senderTimeStamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MTBlock2 {\n");
    
    sb.append("    block2DeliveryMonitor: ").append(toIndentedString(block2DeliveryMonitor)).append("\n");
    sb.append("    block2InOutInd: ").append(toIndentedString(block2InOutInd)).append("\n");
    sb.append("    block2MIRDate: ").append(toIndentedString(block2MIRDate)).append("\n");
    sb.append("    block2MIRLogicalTerminal: ").append(toIndentedString(block2MIRLogicalTerminal)).append("\n");
    sb.append("    block2MIRSeqNum: ").append(toIndentedString(block2MIRSeqNum)).append("\n");
    sb.append("    block2MIRSessNum: ").append(toIndentedString(block2MIRSessNum)).append("\n");
    sb.append("    block2MessagePriority: ").append(toIndentedString(block2MessagePriority)).append("\n");
    sb.append("    block2OBSPeriod: ").append(toIndentedString(block2OBSPeriod)).append("\n");
    sb.append("    block2ReceiverAddr: ").append(toIndentedString(block2ReceiverAddr)).append("\n");
    sb.append("    block2ReceiverOutDate: ").append(toIndentedString(block2ReceiverOutDate)).append("\n");
    sb.append("    block2ReceiverOutTime: ").append(toIndentedString(block2ReceiverOutTime)).append("\n");
    sb.append("    block2SenderInTime: ").append(toIndentedString(block2SenderInTime)).append("\n");
    sb.append("    receiverTimeStamp: ").append(toIndentedString(receiverTimeStamp)).append("\n");
    sb.append("    senderTimeStamp: ").append(toIndentedString(senderTimeStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
