/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MTBlock1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class MTBlock1 {
  @SerializedName("block1ApplicationId")
  private String block1ApplicationId = null;

  @SerializedName("block1LogicalTerminal")
  private String block1LogicalTerminal = null;

  @SerializedName("block1SequenceNumber")
  private String block1SequenceNumber = null;

  @SerializedName("block1ServiceId")
  private String block1ServiceId = null;

  @SerializedName("block1SessionNumber")
  private String block1SessionNumber = null;

  public MTBlock1 block1ApplicationId(String block1ApplicationId) {
    this.block1ApplicationId = block1ApplicationId;
    return this;
  }

   /**
   * Get block1ApplicationId
   * @return block1ApplicationId
  **/
  @Schema(description = "")
  public String getBlock1ApplicationId() {
    return block1ApplicationId;
  }

  public void setBlock1ApplicationId(String block1ApplicationId) {
    this.block1ApplicationId = block1ApplicationId;
  }

  public MTBlock1 block1LogicalTerminal(String block1LogicalTerminal) {
    this.block1LogicalTerminal = block1LogicalTerminal;
    return this;
  }

   /**
   * Get block1LogicalTerminal
   * @return block1LogicalTerminal
  **/
  @Schema(description = "")
  public String getBlock1LogicalTerminal() {
    return block1LogicalTerminal;
  }

  public void setBlock1LogicalTerminal(String block1LogicalTerminal) {
    this.block1LogicalTerminal = block1LogicalTerminal;
  }

  public MTBlock1 block1SequenceNumber(String block1SequenceNumber) {
    this.block1SequenceNumber = block1SequenceNumber;
    return this;
  }

   /**
   * Get block1SequenceNumber
   * @return block1SequenceNumber
  **/
  @Schema(description = "")
  public String getBlock1SequenceNumber() {
    return block1SequenceNumber;
  }

  public void setBlock1SequenceNumber(String block1SequenceNumber) {
    this.block1SequenceNumber = block1SequenceNumber;
  }

  public MTBlock1 block1ServiceId(String block1ServiceId) {
    this.block1ServiceId = block1ServiceId;
    return this;
  }

   /**
   * Get block1ServiceId
   * @return block1ServiceId
  **/
  @Schema(description = "")
  public String getBlock1ServiceId() {
    return block1ServiceId;
  }

  public void setBlock1ServiceId(String block1ServiceId) {
    this.block1ServiceId = block1ServiceId;
  }

  public MTBlock1 block1SessionNumber(String block1SessionNumber) {
    this.block1SessionNumber = block1SessionNumber;
    return this;
  }

   /**
   * Get block1SessionNumber
   * @return block1SessionNumber
  **/
  @Schema(description = "")
  public String getBlock1SessionNumber() {
    return block1SessionNumber;
  }

  public void setBlock1SessionNumber(String block1SessionNumber) {
    this.block1SessionNumber = block1SessionNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MTBlock1 mtBlock1 = (MTBlock1) o;
    return Objects.equals(this.block1ApplicationId, mtBlock1.block1ApplicationId) &&
        Objects.equals(this.block1LogicalTerminal, mtBlock1.block1LogicalTerminal) &&
        Objects.equals(this.block1SequenceNumber, mtBlock1.block1SequenceNumber) &&
        Objects.equals(this.block1ServiceId, mtBlock1.block1ServiceId) &&
        Objects.equals(this.block1SessionNumber, mtBlock1.block1SessionNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(block1ApplicationId, block1LogicalTerminal, block1SequenceNumber, block1ServiceId, block1SessionNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MTBlock1 {\n");
    
    sb.append("    block1ApplicationId: ").append(toIndentedString(block1ApplicationId)).append("\n");
    sb.append("    block1LogicalTerminal: ").append(toIndentedString(block1LogicalTerminal)).append("\n");
    sb.append("    block1SequenceNumber: ").append(toIndentedString(block1SequenceNumber)).append("\n");
    sb.append("    block1ServiceId: ").append(toIndentedString(block1ServiceId)).append("\n");
    sb.append("    block1SessionNumber: ").append(toIndentedString(block1SessionNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
