/*
 * REST Api Documentation
 * REST Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CommonPk;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Tag13C
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-13T21:08:51.033009+05:30[Asia/Kolkata]")
public class Tag13C {
  @SerializedName("commonPk")
  private CommonPk commonPk = null;

  @SerializedName("tag13CCode")
  private String tag13CCode = null;

  @SerializedName("tag13CIndex")
  private Long tag13CIndex = null;

  @SerializedName("tag13COffset")
  private String tag13COffset = null;

  @SerializedName("tag13CSign")
  private String tag13CSign = null;

  @SerializedName("tag13CSkey")
  private Long tag13CSkey = null;

  @SerializedName("tag13CTime")
  private String tag13CTime = null;

  public Tag13C commonPk(CommonPk commonPk) {
    this.commonPk = commonPk;
    return this;
  }

   /**
   * Get commonPk
   * @return commonPk
  **/
  @Schema(description = "")
  public CommonPk getCommonPk() {
    return commonPk;
  }

  public void setCommonPk(CommonPk commonPk) {
    this.commonPk = commonPk;
  }

  public Tag13C tag13CCode(String tag13CCode) {
    this.tag13CCode = tag13CCode;
    return this;
  }

   /**
   * Get tag13CCode
   * @return tag13CCode
  **/
  @Schema(description = "")
  public String getTag13CCode() {
    return tag13CCode;
  }

  public void setTag13CCode(String tag13CCode) {
    this.tag13CCode = tag13CCode;
  }

  public Tag13C tag13CIndex(Long tag13CIndex) {
    this.tag13CIndex = tag13CIndex;
    return this;
  }

   /**
   * Get tag13CIndex
   * @return tag13CIndex
  **/
  @Schema(description = "")
  public Long getTag13CIndex() {
    return tag13CIndex;
  }

  public void setTag13CIndex(Long tag13CIndex) {
    this.tag13CIndex = tag13CIndex;
  }

  public Tag13C tag13COffset(String tag13COffset) {
    this.tag13COffset = tag13COffset;
    return this;
  }

   /**
   * Get tag13COffset
   * @return tag13COffset
  **/
  @Schema(description = "")
  public String getTag13COffset() {
    return tag13COffset;
  }

  public void setTag13COffset(String tag13COffset) {
    this.tag13COffset = tag13COffset;
  }

  public Tag13C tag13CSign(String tag13CSign) {
    this.tag13CSign = tag13CSign;
    return this;
  }

   /**
   * Get tag13CSign
   * @return tag13CSign
  **/
  @Schema(description = "")
  public String getTag13CSign() {
    return tag13CSign;
  }

  public void setTag13CSign(String tag13CSign) {
    this.tag13CSign = tag13CSign;
  }

  public Tag13C tag13CSkey(Long tag13CSkey) {
    this.tag13CSkey = tag13CSkey;
    return this;
  }

   /**
   * Get tag13CSkey
   * @return tag13CSkey
  **/
  @Schema(description = "")
  public Long getTag13CSkey() {
    return tag13CSkey;
  }

  public void setTag13CSkey(Long tag13CSkey) {
    this.tag13CSkey = tag13CSkey;
  }

  public Tag13C tag13CTime(String tag13CTime) {
    this.tag13CTime = tag13CTime;
    return this;
  }

   /**
   * Get tag13CTime
   * @return tag13CTime
  **/
  @Schema(description = "")
  public String getTag13CTime() {
    return tag13CTime;
  }

  public void setTag13CTime(String tag13CTime) {
    this.tag13CTime = tag13CTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tag13C tag13C = (Tag13C) o;
    return Objects.equals(this.commonPk, tag13C.commonPk) &&
        Objects.equals(this.tag13CCode, tag13C.tag13CCode) &&
        Objects.equals(this.tag13CIndex, tag13C.tag13CIndex) &&
        Objects.equals(this.tag13COffset, tag13C.tag13COffset) &&
        Objects.equals(this.tag13CSign, tag13C.tag13CSign) &&
        Objects.equals(this.tag13CSkey, tag13C.tag13CSkey) &&
        Objects.equals(this.tag13CTime, tag13C.tag13CTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonPk, tag13CCode, tag13CIndex, tag13COffset, tag13CSign, tag13CSkey, tag13CTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tag13C {\n");
    
    sb.append("    commonPk: ").append(toIndentedString(commonPk)).append("\n");
    sb.append("    tag13CCode: ").append(toIndentedString(tag13CCode)).append("\n");
    sb.append("    tag13CIndex: ").append(toIndentedString(tag13CIndex)).append("\n");
    sb.append("    tag13COffset: ").append(toIndentedString(tag13COffset)).append("\n");
    sb.append("    tag13CSign: ").append(toIndentedString(tag13CSign)).append("\n");
    sb.append("    tag13CSkey: ").append(toIndentedString(tag13CSkey)).append("\n");
    sb.append("    tag13CTime: ").append(toIndentedString(tag13CTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
